using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace GSCode.Parser.DFA;

internal record class ScrEntityField(ScrDataTypes Type, bool ReadOnly = false);

/// <summary>
/// A registry that tracks entity types and their fields.
/// </summary>
internal static class ScrEntityRegistry
{
    private static readonly Dictionary<string, ScrEntityField> _weaponFields = new([
        new("aifusetime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("projexplosionsound", new(ScrDataTypes.String, ReadOnly: true)),
        new("projexplosionsoundplayer", new(ScrDataTypes.String, ReadOnly: true)),
        new("projSmokeStartSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("projSmokeLoopSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("projSmokeEndSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("meleechargerange", new(ScrDataTypes.Float, ReadOnly: true)),
        new("meleelungerange", new(ScrDataTypes.Float, ReadOnly: true)),
        new("dogibbing", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("dogibbingonmelee", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("doannihilate", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("doblowback", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("maxgibdistance", new(ScrDataTypes.Float, ReadOnly: true)),
        new("leftarc", new(ScrDataTypes.Float, ReadOnly: true)),
        new("rightarc", new(ScrDataTypes.Float, ReadOnly: true)),
        new("toparc", new(ScrDataTypes.Float, ReadOnly: true)),
        new("bottomarc", new(ScrDataTypes.Float, ReadOnly: true)),
        new("clipmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("fightdist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("maxdist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("spinuptime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("spindowntime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("fuellife", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isboltaction", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isdisallowatmatchstart", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("firesound", new(ScrDataTypes.String, ReadOnly: true)),
        new("firesoundplayer", new(ScrDataTypes.String, ReadOnly: true)),
        new("blocksprone", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("iscliponly", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("lockOnRadius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockOnLossRadius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("requirelockontofire", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("setusedstat", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("maxinstancesallowed", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isemp", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isflash", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isstun", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("bulletImpactExplode", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("doempdestroyfx", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("dostun", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("dodamagefeedback", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("dohackedstats", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("hackertriggerorigintag", new(ScrDataTypes.String, ReadOnly: true)),
        new("spawnInfluencer", new(ScrDataTypes.String, ReadOnly: true)),
        new("anyplayercanretrieve", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("istacticalinsertion", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isvaluable", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("destroyablebytrophysystem", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("drawoffhandmodelinhand", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("disallowatmatchstart", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("nonstowedweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isscavengable", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("doesfiredamage", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ignoresflakjacket", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("notkillstreak", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isgameplayweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("issupplydropweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("skipbattlechatterkill", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("skipbattlechatterreload", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("doNotDamageOwner", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("destroysEquipment", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("forcedamageshellshockandrumble", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isaikillstreakdamage", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ignoreteamkills", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("teamkillpenaltyscale", new(ScrDataTypes.Float, ReadOnly: true)),
        new("vehicleprojectiledamagescalar", new(ScrDataTypes.Float, ReadOnly: true)),
        new("vehicleprojectilesplashdamagescalar", new(ScrDataTypes.Float, ReadOnly: true)),
        new("isballisticknife", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isperkbottle", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("skiplowammovox", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isflourishweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ishybridweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("disableDeploy", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("issniperweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ishacktoolweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("meleeIgnoresLightArmor", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ignoresLightArmor", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ignoresPowerArmor", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("soundRattleRangeMin", new(ScrDataTypes.Int, ReadOnly: true)),
        new("soundRattleRangeMax", new(ScrDataTypes.Int, ReadOnly: true)),
        new("grappleweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("burstCount", new(ScrDataTypes.Int, ReadOnly: true)),
        new("weaponHeadObjectiveHeight", new(ScrDataTypes.Float, ReadOnly: true)),
        new("enemycrosshairrange", new(ScrDataTypes.Float, ReadOnly: true)),
        new("unlimitedammo", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isnotdroppable", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("damageAlwaysKillsPlayer", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("damageToOwnerScalar", new(ScrDataTypes.Float, ReadOnly: true)),
        new("viewmodels", new(ScrDataTypes.String, ReadOnly: true)),
        new("frontendmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("worldmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("worlddamagedmodel1", new(ScrDataTypes.String, ReadOnly: true)),
        new("worlddamagedmodel2", new(ScrDataTypes.String, ReadOnly: true)),
        new("worlddamagedmodel3", new(ScrDataTypes.String, ReadOnly: true)),
        new("stowedmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("shownenemyequip", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("shownenemyexplo", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("shownretrievable", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("lockonminrange", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockonscreenradius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockonanglehorizontal", new(ScrDataTypes.Float, ReadOnly: true)),
        new("lockonanglevertical", new(ScrDataTypes.Float, ReadOnly: true)),
        new("lockonlossanglehorizontal", new(ScrDataTypes.Float, ReadOnly: true)),
        new("lockonlossanglevertical", new(ScrDataTypes.Float, ReadOnly: true)),
        new("isvalid", new(ScrDataTypes.Int, ReadOnly: true)),
        new("rootweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("attachments", new(ScrDataTypes.Int, ReadOnly: true)),
        new("supportedattachments", new(ScrDataTypes.Int, ReadOnly: true)),
        new("startammo", new(ScrDataTypes.Int, ReadOnly: true)),
        new("maxammo", new(ScrDataTypes.Int, ReadOnly: true)),
        new("guidedmissiletype", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockontype", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isrocketlauncher", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("lockonSeekerSearchSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("lockonSeekerSearchSoundLoops", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("lockonSeekerLockedSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("lockonSeekerLockedSoundLoops", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("lockonTargetLockedSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("lockonTargetLockedSoundLoops", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("lockonTargetFiredOnSound", new(ScrDataTypes.String, ReadOnly: true)),
        new("lockonTargetFiredOnSoundLoops", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("type", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isbulletweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isgrenadeweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isprojectileweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isgasweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isriotshield", new(ScrDataTypes.Int, ReadOnly: true)),
        new("weapclass", new(ScrDataTypes.Int, ReadOnly: true)),
        new("iskillstreak", new(ScrDataTypes.Int, ReadOnly: true)),
        new("iscarriedkillstreak", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("offhandclass", new(ScrDataTypes.Int, ReadOnly: true)),
        new("offhandslot", new(ScrDataTypes.Int, ReadOnly: true)),
        new("islethalgrenade", new(ScrDataTypes.Int, ReadOnly: true)),
        new("istacticalgrenade", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isequipment", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isspecificuse", new(ScrDataTypes.Int, ReadOnly: true)),
        new("inventorytype", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isprimary", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isitem", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isaltmode", new(ScrDataTypes.Int, ReadOnly: true)),
        new("projexplosiontype", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isgadget", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isheroweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_heroversion_2_0", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_breadcrumbduration", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_flickerondamage", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_flickeronpowerloss", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_flickeronpowerlow", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_max_hitpoints", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_power_consume_on_ammo_use", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_powermoveloss", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_powermovespeed", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_powergainscorefactor", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_powergainscoreignoreself", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_powergainscoreignorewhenactive", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_powerofflossondamage", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_poweronlossondamage", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_powerreplenishfactor", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_power_reset_on_spawn", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_power_reset_on_class_change", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_power_reset_on_team_change", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_power_reset_on_round_switch", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_power_round_end_active_penalty", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gadget_power_usage_rate", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_powertakedowngain", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_takedownrevealtime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_type", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_shieldreflectpowergain", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_shieldreflectpowerloss", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_shockfield_radius", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_shockfield_damage", new(ScrDataTypes.Float, ReadOnly: true)),
        new("gadget_turnoff_onempjammed", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("name", new(ScrDataTypes.String, ReadOnly: true)),
        new("displayname", new(ScrDataTypes.String, ReadOnly: true)),
        new("firetype", new(ScrDataTypes.Int, ReadOnly: true)),
        new("isfullauto", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("issemiauto", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isburstfire", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isstackedfire", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isalllockedfire", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("ischargeshot", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("islauncher", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("clipsize", new(ScrDataTypes.Int, ReadOnly: true)),
        new("shotcount", new(ScrDataTypes.Int, ReadOnly: true)),
        new("ismeleeweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("deathcamtime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("firetime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("reloadtime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("meleetime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("meleepowertime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("meleepowertimeLeft", new(ScrDataTypes.Int, ReadOnly: true)),
        new("meleechargetime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("meleedamage", new(ScrDataTypes.Int, ReadOnly: true)),
        new("altweapon", new(ScrDataTypes.String, ReadOnly: true)),
        new("dualwieldweapon", new(ScrDataTypes.String, ReadOnly: true)),
        new("isdualwield", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("fusetime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("istimeddetonation", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("allowsDetonationDuringReload", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("proximitydetonation", new(ScrDataTypes.Int, ReadOnly: true)),
        new("proximityalarminnerradius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("proximityalarmouterradius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("proximityalarmactivationdelay", new(ScrDataTypes.Int, ReadOnly: true)),
        new("chaineventradius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("chaineventtime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("chaineventmax", new(ScrDataTypes.Int, ReadOnly: true)),
        new("cookoffholdtime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("multidetonation", new(ScrDataTypes.Int, ReadOnly: true)),
        new("multidetonationfragmentspeed", new(ScrDataTypes.Int, ReadOnly: true)),
        new("explosionradius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("explosioninnerradius", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockonmaxrange", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockonmaxrangenolineofsight", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockonspeed", new(ScrDataTypes.Int, ReadOnly: true)),
        new("ammocountequipment", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_powersprintloss", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_pulse_duration", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_pulse_margin", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_pulse_max_range", new(ScrDataTypes.Int, ReadOnly: true)),
        new("gadget_powermax", new(ScrDataTypes.Int, ReadOnly: true)),
        new("weaponstarthitpoints", new(ScrDataTypes.Int, ReadOnly: true)),
        new("weapondamage1hitpoints", new(ScrDataTypes.Int, ReadOnly: true)),
        new("weapondamage2hitpoints", new(ScrDataTypes.Int, ReadOnly: true)),
        new("weapondamage3hitpoints", new(ScrDataTypes.Int, ReadOnly: true)),
        new("nohitmarker", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("specialpain", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("decoy", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("altoffhand", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("dniweapon", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("pickupsound", new(ScrDataTypes.Int, ReadOnly: true)),
        new("pickupsoundplayer", new(ScrDataTypes.Int, ReadOnly: true)),
        new("burnDuration", new(ScrDataTypes.Int, ReadOnly: true)),
        new("burnDamageInterval", new(ScrDataTypes.Int, ReadOnly: true)),
        new("burnDamage", new(ScrDataTypes.Int, ReadOnly: true))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _genericFields = new([
        new("aitype", new(ScrDataTypes.Object)),
        new("aitypevariant", new(ScrDataTypes.Object)),
        new("angles", new(ScrDataTypes.Vector)),
        new("animname", new(ScrDataTypes.String)),
        new("archetype", new(ScrDataTypes.Object)),
        new("species", new(ScrDataTypes.Object)),
        new("scoretype", new(ScrDataTypes.Object)),
        new("birthtime", new(ScrDataTypes.Int)),
        new("classname", new(ScrDataTypes.String)),
        new("count", new(ScrDataTypes.Int)),
        new("dmg", new(ScrDataTypes.Int)),
        new("health", new(ScrDataTypes.Int)),
        new("index", new(ScrDataTypes.Int)),
        new("item", new(ScrDataTypes.Entity)),
        new("lerp_to_lighter", new(ScrDataTypes.Float)),
        new("lerp_to_darker", new(ScrDataTypes.Float)),
        new("model", new(ScrDataTypes.String)),
        new("origin", new(ScrDataTypes.Vector)),
        new("script_animname", new(ScrDataTypes.String)),
        new("script_noteworthy", new(ScrDataTypes.String)),
        new("spawnflags", new(ScrDataTypes.Int)),
        new("takedamage", new(ScrDataTypes.Bool)),
        new("allowdeath", new(ScrDataTypes.Bool)),
        new("target", new(ScrDataTypes.String)),
        new("targetname", new(ScrDataTypes.String)),
        new("team", new(ScrDataTypes.Int))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _hudElemFields = new([
        new("x", new(ScrDataTypes.Float)),
        new("y", new(ScrDataTypes.Float)),
        new("z", new(ScrDataTypes.Float)),
        new("fontscale", new(ScrDataTypes.Float)),
        new("font", new(ScrDataTypes.Int)),
        new("alignx", new(ScrDataTypes.Int)),
        new("aligny", new(ScrDataTypes.Int)),
        new("horzalign", new(ScrDataTypes.Int)),
        new("vertalign", new(ScrDataTypes.Int)),
        new("color", new(ScrDataTypes.Int)),
        new("alpha", new(ScrDataTypes.Int)),
        new("label", new(ScrDataTypes.Int)),
        new("sort", new(ScrDataTypes.Float)),
        new("foreground", new(ScrDataTypes.Bool)),
        new("hidewhendead", new(ScrDataTypes.Bool)),
        new("hidewheninkillcam", new(ScrDataTypes.Bool)),
        new("hidewhenindemo", new(ScrDataTypes.Bool)),
        new("immunetodemogamehudsettings", new(ScrDataTypes.Bool)),
        new("immunetodemofreecamera", new(ScrDataTypes.Bool)),
        new("hidewhileremotecontrolling", new(ScrDataTypes.Bool)),
        new("hidewheninmenu", new(ScrDataTypes.Bool)),
        new("hidewheninscope", new(ScrDataTypes.Bool)),
        new("fadewhentargeted", new(ScrDataTypes.Bool)),
        new("fontstyle3d", new(ScrDataTypes.Int)),
        new("font3duseglowcolor", new(ScrDataTypes.Bool)),
        new("showplayerteamhudelemtospectator", new(ScrDataTypes.Bool)),
        new("glowcolor", new(ScrDataTypes.Int)),
        new("glowalpha", new(ScrDataTypes.Int)),
        new("archived", new(ScrDataTypes.Bool))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _vehicleNodeFields = new([
        new("targetname", new(ScrDataTypes.String)),
        new("target", new(ScrDataTypes.String)),
        new("target2", new(ScrDataTypes.String)),
        new("script_linkname", new(ScrDataTypes.String)),
        new("script_noteworthy", new(ScrDataTypes.String)),
        new("origin", new(ScrDataTypes.Vector)),
        new("angles", new(ScrDataTypes.Vector)),
        new("speed", new(ScrDataTypes.Float)),
        new("radius", new(ScrDataTypes.Float)),
        new("lookahead", new(ScrDataTypes.Float)),
        new("tension", new(ScrDataTypes.Float)),
        new("spawnflags", new(ScrDataTypes.Int))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _pathNodeFields = new([
        new("targetname", new(ScrDataTypes.String, ReadOnly: true)),
        new("target", new(ScrDataTypes.String, ReadOnly: true)),
        new("animscript", new(ScrDataTypes.String, ReadOnly: true)),
        new("script_linkname", new(ScrDataTypes.String, ReadOnly: true)),
        new("script_noteworthy", new(ScrDataTypes.String, ReadOnly: true)),
        new("origin", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("angles", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("spawnflags", new(ScrDataTypes.Int, ReadOnly: true)),
        new("movementtype_ignore", new(ScrDataTypes.Int, ReadOnly: true)),
        new("movementtype_require", new(ScrDataTypes.Int, ReadOnly: true)),
        new("type", new(ScrDataTypes.Int, ReadOnly: true)),
        new("suspended", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("cost_modifier", new(ScrDataTypes.Float, ReadOnly: true))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _aiTypeFields = new([
        new("hero", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("canflank", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("accuratefire", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("aggressivemode", new(ScrDataTypes.Bool, ReadOnly: true))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _vehicleFields = new([
        new("vehicleclass", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehicletype", new(ScrDataTypes.String)),
        new("scriptvehicletype", new(ScrDataTypes.String, ReadOnly: true)),
        new("playerdrivenversion", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehspeed", new(ScrDataTypes.Float, ReadOnly: true)),
        new("velocity", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("radius", new(ScrDataTypes.Float, ReadOnly: true)),
        new("height", new(ScrDataTypes.Float, ReadOnly: true)),
        new("turretrotscale", new(ScrDataTypes.Float)),
        new("accuracy_turret", new(ScrDataTypes.Float)),
        new("accuracy_gunner1", new(ScrDataTypes.Float)),
        new("accuracy_gunner2", new(ScrDataTypes.Float)),
        new("accuracy_gunner3", new(ScrDataTypes.Float)),
        new("accuracy_gunner4", new(ScrDataTypes.Float)),
        new("vehmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehmodelenemy", new(ScrDataTypes.String, ReadOnly: true)),
        new("deathmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehviewmodel", new(ScrDataTypes.String, ReadOnly: true)),
        new("modelswapdelay", new(ScrDataTypes.Float, ReadOnly: true)),
        new("radiusdamagemin", new(ScrDataTypes.Float, ReadOnly: true)),
        new("radiusdamagemax", new(ScrDataTypes.Float, ReadOnly: true)),
        new("radiusdamageradius", new(ScrDataTypes.Float, ReadOnly: true)),
        new("shootshock", new(ScrDataTypes.String, ReadOnly: true)),
        new("rumbletype", new(ScrDataTypes.String, ReadOnly: true)),
        new("rumblescale", new(ScrDataTypes.Float, ReadOnly: true)),
        new("rumbleduration", new(ScrDataTypes.Float, ReadOnly: true)),
        new("rumbleradius", new(ScrDataTypes.Float, ReadOnly: true)),
        new("rumblebasetime", new(ScrDataTypes.Float, ReadOnly: true)),
        new("rumbleadditionaltime", new(ScrDataTypes.Float, ReadOnly: true)),
        new("healthdefault", new(ScrDataTypes.Int, ReadOnly: true)),
        new("turretweapon", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("addtocompass", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("isphysicsvehicle", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("pathpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("pathlookpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("pathwidth", new(ScrDataTypes.Float, ReadOnly: true)),
        new("pathwidthlookaheadfrac", new(ScrDataTypes.Float)),
        new("pathdistancetraveled", new(ScrDataTypes.Float, ReadOnly: true)),
        new("heliheightlockoffset", new(ScrDataTypes.Float)),
        new("drivebysoundtime0", new(ScrDataTypes.Float, ReadOnly: true)),
        new("drivebysoundtime1", new(ScrDataTypes.Float, ReadOnly: true)),
        new("scriptbundlesettings", new(ScrDataTypes.String, ReadOnly: true)),
        new("assassinationbundle", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehicleridersbundle", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehicleridersrobotbundle", new(ScrDataTypes.String, ReadOnly: true)),
        new("vehkilloccupantsondeath", new(ScrDataTypes.Bool)),
        new("vehunlinkoccupantsondeath", new(ScrDataTypes.Bool)),
        new("vehcheckforpredictedcrash", new(ScrDataTypes.Bool)),
        new("vehonpath", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("vehaircraftcollisionenabled", new(ScrDataTypes.Bool)),
        new("turretontarget", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("turretonvistarget", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gunner1ontarget", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gunner2ontarget", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("physicslaunchdeathscale", new(ScrDataTypes.Float, ReadOnly: true)),
        new("jumpforce", new(ScrDataTypes.Float, ReadOnly: true)),
        new("predictedCollisionTime", new(ScrDataTypes.Float)),
        new("glasscollision_alt", new(ScrDataTypes.Bool))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _sentientFields = new([
        new("script_owner", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("threatbias", new(ScrDataTypes.Int)),
        new("threatbiasgroup", new(ScrDataTypes.Int, ReadOnly: true)),
        new("attacker", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("attackercount", new(ScrDataTypes.Int, ReadOnly: true)),
        new("node", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("prevnode", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("enemy", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("enemylastseenpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("scriptenemy", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("scriptenemytag", new(ScrDataTypes.String, ReadOnly: true)),
        new("syncedmeleetarget", new(ScrDataTypes.Entity)),
        new("ignoreme", new(ScrDataTypes.Bool)),
        new("ignoreall", new(ScrDataTypes.Bool)),
        new("ignoreforfriendlyfire", new(ScrDataTypes.Bool)),
        new("ignorevortices", new(ScrDataTypes.Bool)),
        new("maxvisibledist", new(ScrDataTypes.Float)),
        new("maxseenfovcosine", new(ScrDataTypes.Float)),
        new("maxseenfovcosinez", new(ScrDataTypes.Float)),
        new("silentshot", new(ScrDataTypes.Bool)),
        new("surprisedbymedistsq", new(ScrDataTypes.Float)),
        new("attackeraccuracy", new(ScrDataTypes.Float)),
        new("ignorenavmeshtriggers", new(ScrDataTypes.Bool)),
        new("ignorebulletdamage", new(ScrDataTypes.Bool)),
        new("inmeleecharge", new(ScrDataTypes.Bool)),
        new("updatesight", new(ScrDataTypes.Bool)),
        new("fovcosine", new(ScrDataTypes.Float)),
        new("fovcosinebusy", new(ScrDataTypes.Float)),
        new("fovcosinez", new(ScrDataTypes.Float)),
        new("maxsightdistsqrd", new(ScrDataTypes.Float)),
        new("sightlatency", new(ScrDataTypes.Float)),
        new("ignoreclosefoliage", new(ScrDataTypes.Bool)),
        new("pacifist", new(ScrDataTypes.Bool)),
        new("pacifistwait", new(ScrDataTypes.Int)),
        new("goodenemyonly", new(ScrDataTypes.Bool)),
        new("ignoreexplosionevents", new(ScrDataTypes.Bool)),
        new("favoriteenemy", new(ScrDataTypes.Entity)),
        new("highlyawareradius", new(ScrDataTypes.Float)),
        new("drawoncompass", new(ScrDataTypes.Bool)),
        new("activatecrosshair", new(ScrDataTypes.Bool)),
        new("attackercountthreatscale", new(ScrDataTypes.Float)),
        new("currentenemythreatscale", new(ScrDataTypes.Float)),
        new("recentattackerthreatscale", new(ScrDataTypes.Float)),
        new("coverthreatscale", new(ScrDataTypes.Float)),
        new("goalradius", new(ScrDataTypes.Float)),
        new("goalheight", new(ScrDataTypes.Float)),
        new("goalpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("goalent", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("goalforced", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("fixednode", new(ScrDataTypes.Bool)),
        new("fixednodesaferadius", new(ScrDataTypes.Float)),
        new("goalangle", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("isatanchor", new(ScrDataTypes.Bool))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _actorFields = new([
        new("isdog", new(ScrDataTypes.Int, ReadOnly: true)),
        new("missinglegs", new(ScrDataTypes.Int)),
        new("accuracy", new(ScrDataTypes.Float)),
        new("perfectaim", new(ScrDataTypes.Bool)),
        new("blindaim", new(ScrDataTypes.Bool)),
        new("holdfire", new(ScrDataTypes.Bool)),
        new("forcefire", new(ScrDataTypes.Bool)),
        new("damagetaken", new(ScrDataTypes.Int, ReadOnly: true)),
        new("damagedir", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("damageyaw", new(ScrDataTypes.Int, ReadOnly: true)),
        new("damagelocation", new(ScrDataTypes.String, ReadOnly: true)),
        new("damageweapon", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("damagemod", new(ScrDataTypes.String, ReadOnly: true)),
        new("proneok", new(ScrDataTypes.Int, ReadOnly: true)),
        new("walkdist", new(ScrDataTypes.Float)),
        new("dontavoidplayer", new(ScrDataTypes.Bool)),
        new("desiredangle", new(ScrDataTypes.Float, ReadOnly: true)),
        new("newenemyreactionpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("newenemyreaction", new(ScrDataTypes.Bool)),
        new("newenemyreactiondistsq", new(ScrDataTypes.Float)),
        new("ignoresuppression", new(ScrDataTypes.Bool)),
        new("suppressionwait", new(ScrDataTypes.Float)),
        new("suppressionduration", new(ScrDataTypes.Float)),
        new("suppressionstarttime", new(ScrDataTypes.Int, ReadOnly: true)),
        new("suppressionmeter", new(ScrDataTypes.Float, ReadOnly: true)),
        new("weapon", new(ScrDataTypes.Entity)),
        new("secondaryweapon", new(ScrDataTypes.Entity)),
        new("primaryweapon", new(ScrDataTypes.Entity)),
        new("sidearm", new(ScrDataTypes.Entity)),
        new("meleeweapon", new(ScrDataTypes.Entity)),
        new("ammopouch", new(ScrDataTypes.Entity)),
        new("grenadeawareness", new(ScrDataTypes.Float)),
        new("grenade", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("grenadeweapon", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("grenadeammo", new(ScrDataTypes.Float)),
        new("grenadethrowback", new(ScrDataTypes.Bool)),
        new("allowpain", new(ScrDataTypes.Bool)),
        new("blockingpain", new(ScrDataTypes.Bool)),
        new("diequietly", new(ScrDataTypes.Bool)),
        new("skipDeath", new(ScrDataTypes.Bool)),
        new("doingambush", new(ScrDataTypes.Bool)),
        new("combatmode", new(ScrDataTypes.Int)),
        new("alertlevel", new(ScrDataTypes.Int)),
        new("alertlevelint", new(ScrDataTypes.Float)),
        new("awarenesslevelcurrent", new(ScrDataTypes.Int)),
        new("awarenesslevelprevious", new(ScrDataTypes.Int)),
        new("ignoretriggers", new(ScrDataTypes.Int)),
        new("pushable", new(ScrDataTypes.Int)),
        new("enableterrainik", new(ScrDataTypes.Int)),
        new("noplayermeleeblood", new(ScrDataTypes.Int)),
        new("clamptonavmesh", new(ScrDataTypes.Int)),
        new("gibbed", new(ScrDataTypes.Int)),
        new("groundrelativepose", new(ScrDataTypes.Int)),
        new("dropweapon", new(ScrDataTypes.Int, ReadOnly: true)),
        new("groundtype", new(ScrDataTypes.String, ReadOnly: true)),
        new("properName", new(ScrDataTypes.String)),
        new("scriptstate", new(ScrDataTypes.String, ReadOnly: true)),
        new("lastscriptstate", new(ScrDataTypes.String, ReadOnly: true)),
        new("statechangereason", new(ScrDataTypes.String, ReadOnly: true)),
        new("nodeoffsetpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("pathstartpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("pathgoalpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("pathrandompercent", new(ScrDataTypes.Int)),
        new("usechokepoints", new(ScrDataTypes.Bool)),
        new("lastenemysightpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("pathenemylookahead", new(ScrDataTypes.Float)),
        new("pathenemyfightdist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("ignorepathenemyfightdist", new(ScrDataTypes.Bool)),
        new("ignorerunandgundist", new(ScrDataTypes.Bool)),
        new("runandgundist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("meleeattackdist", new(ScrDataTypes.Float)),
        new("movemode", new(ScrDataTypes.String, ReadOnly: true)),
        new("usecombatscriptatcover", new(ScrDataTypes.Bool)),
        new("safetochangescript", new(ScrDataTypes.Bool)),
        new("usegoalanimweight", new(ScrDataTypes.Bool)),
        new("keepclaimednode", new(ScrDataTypes.Bool)),
        new("keepclaimednodeifvalid", new(ScrDataTypes.Bool)),
        new("coversearchinterval", new(ScrDataTypes.Float)),
        new("nextFindBestCoverTime", new(ScrDataTypes.Float)),
        new("badplaceawareness", new(ScrDataTypes.Float)),
        new("nogrenadereturnthrow", new(ScrDataTypes.Bool)),
        new("goodshootpos", new(ScrDataTypes.Vector)),
        new("goodshootposvalid", new(ScrDataTypes.Bool)),
        new("flashbangimmunity", new(ScrDataTypes.Bool)),
        new("lookaheaddir", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("lookaheaddist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("prevanimdelta", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("exposedduration", new(ScrDataTypes.Float)),
        new("pathwaittime", new(ScrDataTypes.Float)),
        new("lastpathtime", new(ScrDataTypes.Float)),
        new("isarriving", new(ScrDataTypes.Bool)),
        new("isarrivalpending", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("engagemindist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("engageminfalloffdist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("engagemaxdist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("engagemaxfalloffdist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("finalaccuracy", new(ScrDataTypes.Float, ReadOnly: true)),
        new("noattackeraccuracymod", new(ScrDataTypes.Bool)),
        new("maxfaceenemydist", new(ScrDataTypes.Float, ReadOnly: true)),
        new("prevrelativedir", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("relativedir", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("gunblockedbywall", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("fixedlinkyawonly", new(ScrDataTypes.Bool)),
        new("weaponaccuracy", new(ScrDataTypes.Float, ReadOnly: true)),
        new("movementtype", new(ScrDataTypes.String)),
        new("arrivalfinalpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("exitPos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("predictedExitPos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("predictedArrivalDirectionValid", new(ScrDataTypes.Bool)),
        new("arrivalfinalyaw", new(ScrDataTypes.Float, ReadOnly: true)),
        new("firemode", new(ScrDataTypes.Int, ReadOnly: true)),
        new("traversestartnode", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("traverseendnode", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("traversalstartpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("traversalendpos", new(ScrDataTypes.Vector, ReadOnly: true)),
        new("manualtraversemode", new(ScrDataTypes.Bool)),
        new("script_accuracy", new(ScrDataTypes.Float)),
        new("bulletsinclip", new(ScrDataTypes.Float)),
        new("actor_id", new(ScrDataTypes.Int, ReadOnly: true)),
        new("animtranslationscale", new(ScrDataTypes.Float)),
        new("pathablematerial", new(ScrDataTypes.Int))
    ]);

    private static readonly Dictionary<string, ScrEntityField> _playerFields = new([
        new("playername", new(ScrDataTypes.String, ReadOnly: true)),
        new("sessionteam", new(ScrDataTypes.String)),
        new("name", new(ScrDataTypes.String, ReadOnly: true)),
        new("maxhealth", new(ScrDataTypes.Int)),
        new("weaponhealth", new(ScrDataTypes.Int)),
        new("hasspyplane", new(ScrDataTypes.Int)),
        new("hassatellite", new(ScrDataTypes.Int)),
        new("disallowvehicleusage", new(ScrDataTypes.Bool)),
        new("downs", new(ScrDataTypes.Int)),
        new("revives", new(ScrDataTypes.Int)),
        new("kills", new(ScrDataTypes.Int)),
        new("deaths", new(ScrDataTypes.Int)),
        new("assists", new(ScrDataTypes.Int)),
        new("defends", new(ScrDataTypes.Int)),
        new("plants", new(ScrDataTypes.Int)),
        new("defuses", new(ScrDataTypes.Int)),
        new("returns", new(ScrDataTypes.Int)),
        new("captures", new(ScrDataTypes.Int)),
        new("objtime", new(ScrDataTypes.Int)),
        new("destructions", new(ScrDataTypes.Int)),
        new("disables", new(ScrDataTypes.Int)),
        new("escorts", new(ScrDataTypes.Int)),
        new("carries", new(ScrDataTypes.Int)),
        new("throws", new(ScrDataTypes.Int)),
        new("survived", new(ScrDataTypes.Int)),
        new("stabs", new(ScrDataTypes.Int)),
        new("tomahawks", new(ScrDataTypes.Int)),
        new("humiliated", new(ScrDataTypes.Int)),
        new("x2score", new(ScrDataTypes.Int)),
        new("headshots", new(ScrDataTypes.Int)),
        new("agrkills", new(ScrDataTypes.Int)),
        new("hacks", new(ScrDataTypes.Int)),
        new("pointstowin", new(ScrDataTypes.Int)),
        new("killsconfirmed", new(ScrDataTypes.Int)),
        new("killsdenied", new(ScrDataTypes.Int)),
        new("shotsmissed", new(ScrDataTypes.Int)),
        new("shotshit", new(ScrDataTypes.Int)),
        new("victory", new(ScrDataTypes.Int)),
        new("sbtimeplayed", new(ScrDataTypes.Int)),
        new("incaps", new(ScrDataTypes.Int)),
        new("gems", new(ScrDataTypes.Int)),
        new("skulls", new(ScrDataTypes.Int)),
        new("chickens", new(ScrDataTypes.Int)),
        new("killcamentity", new(ScrDataTypes.Int)),
        new("killcamtargetentity", new(ScrDataTypes.Int)),
        new("killcamweapon", new(ScrDataTypes.Entity)),
        new("killcammod", new(ScrDataTypes.Int)),
        new("spectatekillcam", new(ScrDataTypes.Int)),
        new("score", new(ScrDataTypes.Int)),
        new("sessionstate", new(ScrDataTypes.String)),
        new("statusicon", new(ScrDataTypes.String)),
        new("spectatorclient", new(ScrDataTypes.Int)),
        new("currentspectatingclient", new(ScrDataTypes.Int, ReadOnly: true)),
        new("archivetime", new(ScrDataTypes.Float)),
        new("psoffsettime", new(ScrDataTypes.Int)),
        new("pers", new(ScrDataTypes.Object, ReadOnly: true)),
        new("usingvehicle", new(ScrDataTypes.Bool, ReadOnly: true)),
        new("vehicleposition", new(ScrDataTypes.Int, ReadOnly: true)),
        new("headicon", new(ScrDataTypes.String)),
        new("momentum", new(ScrDataTypes.Int)),
        new("divetoprone", new(ScrDataTypes.Bool)),
        new("sprinting", new(ScrDataTypes.Bool)),
        new("animViewUnlock", new(ScrDataTypes.Bool)),
        new("animInputUnlock", new(ScrDataTypes.Bool)),
        new("animNoClientTransform", new(ScrDataTypes.Bool)),
        new("topdowncamera", new(ScrDataTypes.Bool)),
        new("groundentity", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("viewlockedentity", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("cursorhintent", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("groundsurfacetype", new(ScrDataTypes.String, ReadOnly: true)),
        new("lookatent", new(ScrDataTypes.Entity, ReadOnly: true)),
        new("chargeshotlevel", new(ScrDataTypes.Int, ReadOnly: true)),
        new("lockonentity", new(ScrDataTypes.Entity)),
        new("pivotentity", new(ScrDataTypes.Entity)),
        new("lastdamagetime", new(ScrDataTypes.Int, ReadOnly: true))
    ]);

    public static ScrData GetField(ScrEntityTypes entityType, string fieldName)
    {
        // Find the field amongst the preset fields.
        if(TryFindFieldForEntityType(entityType, fieldName, out ScrEntityField? field))
        {
            return new ScrData(field.Type, readOnly: field.ReadOnly);
        }

        // Otherwise, if it's immutable, then any other field must not be present.
        if(entityType == ScrEntityTypes.Weapon || entityType == ScrEntityTypes.PathNode)
        {
            return ScrData.Undefined();
        }

        // Otherwise, it can have custom fields, so assume any type.
        return ScrData.Default;
    }

    public static ScrEntitySetFieldResult SetField(ScrEntityTypes entityType, string fieldName, ScrData value)
    {
        // Weapon and path node entities are completely immutable.
        if(entityType == ScrEntityTypes.Weapon || entityType == ScrEntityTypes.PathNode)
        {
            return ScrEntitySetFieldResult.EntityImmutable;
        }

        // Find the field amongst the preset fields.
        if(TryFindFieldForEntityType(entityType, fieldName, out ScrEntityField? field))
        {
            // If the field is readonly, it cannot be assigned to.
            if(field.ReadOnly)
            {
                return ScrEntitySetFieldResult.FieldReadOnly;
            }
            // To be a valid assignment, the types must match.
            if(value.Type != field.Type)
            {
                return ScrEntitySetFieldResult.FieldTypeMismatch;
            }
            return ScrEntitySetFieldResult.Success;
        }

        // Otherwise, it can have custom fields, so assume success.
        return ScrEntitySetFieldResult.Success;
    }

    private static bool TryFindFieldForEntityType(ScrEntityTypes entityType, string fieldName, [NotNullWhen(true)] out ScrEntityField? field)
    {
        field = null;
        return entityType switch
        {
            ScrEntityTypes.Weapon => _weaponFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.Vehicle => _vehicleFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.Player => _playerFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.Actor => _actorFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.AiType => _aiTypeFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.PathNode => _pathNodeFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.Sentient => _sentientFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.VehicleNode => _vehicleNodeFields.TryGetValue(fieldName, out field),
            ScrEntityTypes.HudElem => _hudElemFields.TryGetValue(fieldName, out field),
            _ => false
        };
    }
}

internal static class ScrEntityTypeNames
{
    public const string Weapon = "weapon";
    public const string Vehicle = "vehicle";
    public const string Player = "player";
    public const string Actor = "actor";
    public const string AiType = "aitype";
    public const string PathNode = "pathnode";
    public const string Sentient = "sentient";
    public const string VehicleNode = "vehiclenode";
    public const string HudElem = "hudelem";

    public static string TypeToString(ScrEntityTypes type)
    {
        return type switch
        {
            ScrEntityTypes.Weapon => Weapon,
            ScrEntityTypes.Vehicle => Vehicle,
            ScrEntityTypes.Player => Player,
            ScrEntityTypes.Actor => Actor,
            ScrEntityTypes.AiType => AiType,
            ScrEntityTypes.PathNode => PathNode,
            ScrEntityTypes.Sentient => Sentient,
            ScrEntityTypes.VehicleNode => VehicleNode,
            ScrEntityTypes.HudElem => HudElem,
            _ => "unknown"
        };
    }
}

internal enum ScrEntityTypes
{
    Weapon,
    Vehicle,
    Player,
    Actor,
    AiType,
    PathNode,
    Sentient,
    VehicleNode,
    HudElem
}

internal enum ScrEntitySetFieldResult
{
    Success,
    FieldTypeMismatch,
    FieldReadOnly,
    EntityImmutable
}