using System.Diagnostics.CodeAnalysis;
using GSCode.Data;
using GSCode.Data.Models;
using GSCode.Parser.AST;
using GSCode.Parser.Data;
using GSCode.Parser.Lexical;
using GSCode.Parser.SA;
using GSCode.Parser.SPA;
using GSCode.Parser.SPA.Logic.Components;

namespace GSCode.Parser.DFA;

internal ref partial struct TypeFlowAnalyser
{
    private void AddFunctionReferenceToken(Token token, ScrFunction function, SymbolTable symbolTable)
    {
        bool isClassMethod = symbolTable.CurrentClass is not null &&
            symbolTable.CurrentClass.Methods.Any(m => m == function);

        if (isClassMethod)
        {
            Sense.AddSenseToken(token, new ScrMethodReferenceSymbol(token, function, symbolTable.CurrentClass!));
        }
        else
        {
            Sense.AddSenseToken(token, new ScrFunctionReferenceSymbol(token, function));
        }
    }

    private void ValidateArgumentCount(ScrFunction? function, int argCount, Range callRange, string functionName, SymbolFlags flags)
    {
        // Check if we have function information
        if (function is null)
        {
            return; // No function info, can't validate
        }

        // Check if we have any overload information
        if (function.Overloads is null || function.Overloads.Count == 0)
        {
            return; // No signature info, can't validate
        }

        // Determine if this is an unverified built-in (autogenerated/processed from Treyarch's API)
        bool isUnverifiedBuiltIn = flags.HasFlag(SymbolFlags.BuiltIn) &&
                                   (function.Flags.Contains("autogenerated", StringComparer.OrdinalIgnoreCase)
                                   || function.Flags.Contains("processed", StringComparer.OrdinalIgnoreCase));

        // Track the minimum required args across all overloads and maximum allowed args
        int globalMinArgs = int.MaxValue;
        int globalMaxArgs = 0;
        bool anyOverloadHasVararg = false;

        // Check all overloads to see if any match the argument count
        foreach (ScrFunctionOverload overload in function.Overloads)
        {
            // Parameters can be null in some cases (e.g., API functions)
            if (overload?.Parameters is null)
            {
                return; // Can't validate if any overload is missing parameter info
            }

            int minArgs = overload.Parameters.Count(p => p.Mandatory == true);
            int maxArgs = overload.Parameters.Count;
            bool hasVararg = overload.Vararg;

            // Track global bounds
            if (minArgs < globalMinArgs)
            {
                globalMinArgs = minArgs;
            }
            if (maxArgs > globalMaxArgs)
            {
                globalMaxArgs = maxArgs;
            }
            if (hasVararg)
            {
                anyOverloadHasVararg = true;
            }

            // Check if this overload accepts the argument count
            if (hasVararg)
            {
                // Vararg accepts minArgs or more
                if (argCount >= minArgs)
                {
                    return; // Valid for this overload
                }
            }
            else
            {
                // Regular overload: check bounds
                if (argCount >= minArgs && argCount <= maxArgs)
                {
                    return; // Valid for this overload
                }
            }
        }

        // No overload matched - emit diagnostic
        // NOTE: "Too few arguments" is only checked for built-in functions. GSC treats all
        // parameters as optional (missing args become undefined), so we can't reliably validate
        // user-defined functions without a better way to determine required parameters.
        bool isBuiltIn = flags.HasFlag(SymbolFlags.BuiltIn);

        if (isBuiltIn && argCount < globalMinArgs)
        {
            // Too few arguments - report the minimum required (built-ins only)
            if (isUnverifiedBuiltIn)
            {
                AddDiagnostic(callRange, GSCErrorCodes.TooFewArgumentsUnverified, functionName, argCount, globalMinArgs);
            }
            else
            {
                AddDiagnostic(callRange, GSCErrorCodes.TooFewArguments, functionName, argCount, globalMinArgs);
            }
        }
        else if (isBuiltIn && !anyOverloadHasVararg && argCount > globalMaxArgs)
        {
            // Too many arguments - report the maximum allowed (only if no vararg, built-ins only)
            if (isUnverifiedBuiltIn)
            {
                AddDiagnostic(callRange, GSCErrorCodes.TooManyArgumentsUnverified, functionName, argCount, globalMaxArgs);
            }
            else
            {
                AddDiagnostic(callRange, GSCErrorCodes.TooManyArguments, functionName, argCount, globalMaxArgs);
            }
        }
    }

    private void ValidateArgumentTypes(
        ScrFunction? function,
        ScrData[] argTypes,
        FunCallNode call,
        string functionName,
        SymbolFlags flags)
    {
        if (function is null)
        {
            return;
        }
        if (function.Overloads is null || function.Overloads.Count == 0)
        {
            return;
        }
        if (!flags.HasFlag(SymbolFlags.BuiltIn))
        {
            return;  // only check API functions
        }

        bool isUnverified = function.Flags.Contains("autogenerated", StringComparer.OrdinalIgnoreCase)
                         || function.Flags.Contains("autoprocessed", StringComparer.OrdinalIgnoreCase)
                         || function.Flags.Contains("processed", StringComparer.OrdinalIgnoreCase);

        // Find the best matching overload by argument count and type compatibility
        ScrFunctionOverload? matchedOverload = FindBestOverload(function.Overloads, argTypes);

        if (matchedOverload is null)
        {
            return;  // no count-matching overload; count validator handles this
        }

        // Check each argument against expected type
        for (int i = 0; i < Math.Min(argTypes.Length, matchedOverload.Parameters.Count); i++)
        {
            ScrFunctionArg param = matchedOverload.Parameters[i];
            if (param.Type is null)
            {
                continue;  // no type info for this param
            }

            ScrData expectedType = ScrData.FromApiType(param.Type);
            if (expectedType.IsAny())
            {
                continue;  // "any" accepts everything
            }

            // Optional parameters accept undefined (omitted args become undefined in GSC)
            if (param.Mandatory != true)
            {
                expectedType = new ScrData(expectedType.Type | ScrDataTypes.Undefined);
            }

            ScrData actualType = argTypes[i];
            if (actualType.TypeUnknown())
            {
                continue;  // can't validate unknown types
            }

            // Boolean-coercible arguments are allowed for bool parameters via script-style truthy/falsy coercion.
            // IsExactly: the hint must only fire for parameters declared bool — HasType(Bool) would
            // also match int/number parameters, whose flag patterns contain the Bool bit.
            ExprNode? argNode = GetCallArgument(call, i);
            if (expectedType.IsExactly(ScrDataTypes.Bool)
                && actualType.IsCompatibleWith(ScrDataTypes.Int)
                && argNode is not null
                && IsIntLiteral01(argNode, out string? replacement))
            {
                AddIdeDiagnostic(argNode.Range, GSCErrorCodes.PreferBooleanLiteral,
                    replacement, argNode is DataExprNode d ? d.Value?.ToString() ?? "0" : "0");
            }

            if (!IsArgumentTypeCompatible(actualType, expectedType))
            {
                if (argNode is not null)
                {
                    GSCErrorCodes code = isUnverified
                        ? GSCErrorCodes.ArgumentTypeMismatchUnverified
                        : GSCErrorCodes.ArgumentTypeMismatch;
                    AddDiagnostic(argNode.Range, code,
                        i + 1, functionName, expectedType.TypeToString(), actualType.TypeToString());
                }
            }
        }
    }

    private void WarnIfBrokenFunctionUsed(Range range, ScrFunction? function, string functionName)
    {
        if (function is null)
        {
            return;
        }

        if (function.Flags.Contains("broken", StringComparer.OrdinalIgnoreCase))
        {
            AddDiagnostic(range, GSCErrorCodes.BrokenFunctionUsage, functionName);
        }
    }

    /// <summary>
    /// Returns true if the expression is an integer literal 0 or 1, with the suggested boolean replacement.
    /// </summary>
    private static bool IsIntLiteral01(ExprNode expr, [NotNullWhen(true)] out string? replacement)
    {
        if (expr is DataExprNode { Type: ScrDataTypes.Int, Value: int intVal } && (intVal == 0 || intVal == 1))
        {
            replacement = intVal == 0 ? "false" : "true";
            return true;
        }
        replacement = null;
        return false;
    }

    private static ExprNode? GetCallArgument(FunCallNode call, int index)
    {
        int i = 0;
        foreach (ExprNode? arg in call.Arguments.Arguments)
        {
            if (i == index)
            {
                return arg;
            }
            i++;
        }
        return null;
    }

    private static bool IsArgumentTypeCompatible(ScrData actualType, ScrData expectedType)
    {
        if (actualType.IsCompatibleWith(expectedType))
        {
            return true;
        }

        // GSC accepts boolean-coercible values in boolean positions via truthy/falsy coercion.
        if (expectedType.HasType(ScrDataTypes.Bool) && actualType.CanEvaluateToBoolean())
        {
            return true;
        }

        return false;
    }

    /// <summary>
    /// Finds the best matching overload by first filtering by argument count, then scoring
    /// by type compatibility. Returns the overload with the most type-compatible arguments,
    /// or null if no overload matches the argument count.
    /// </summary>
    private static ScrFunctionOverload? FindBestOverload(List<ScrFunctionOverload> overloads, ScrData[] argTypes)
    {
        ScrFunctionOverload? bestOverload = null;
        int bestScore = -1;

        foreach (ScrFunctionOverload? overload in overloads)
        {
            if (overload?.Parameters is null)
            {
                continue;
            }
            int minArgs = overload.Parameters.Count(p => p.Mandatory == true);
            int maxArgs = overload.Parameters.Count;
            bool hasVararg = overload.Vararg;

            // Check argument count
            if (hasVararg)
            {
                if (argTypes.Length < minArgs)
                {
                    continue;
                }
            }
            else
            {
                if (argTypes.Length < minArgs || argTypes.Length > maxArgs)
                {
                    continue;
                }
            }

            // Score by type compatibility
            int score = 0;
            for (int i = 0; i < Math.Min(argTypes.Length, overload.Parameters.Count); i++)
            {
                ScrFunctionArg param = overload.Parameters[i];
                if (param.Type is null)
                {
                    score++;
                    continue;
                }

                ScrData expectedType = ScrData.FromApiType(param.Type);
                if (expectedType.IsAny())
                {
                    score++;
                    continue;
                }

                if (param.Mandatory != true)
                {
                    expectedType = new ScrData(expectedType.Type | ScrDataTypes.Undefined);
                }

                ScrData actualType = argTypes[i];
                if (actualType.TypeUnknown() || IsArgumentTypeCompatible(actualType, expectedType))
                {
                    score++;
                }
            }

            if (score > bestScore)
            {
                bestScore = score;
                bestOverload = overload;
            }
        }

        return bestOverload;
    }

    private void ValidateMethodArgumentTypes(
        ScrFunction? function,
        ScrData[] argTypes,
        MethodCallNode methodCall,
        string functionName,
        SymbolFlags flags)
    {
        if (function is null)
        {
            return;
        }
        if (function.Overloads is null || function.Overloads.Count == 0)
        {
            return;
        }
        if (!flags.HasFlag(SymbolFlags.BuiltIn))
        {
            return;
        }

        bool isUnverified = function.Flags.Contains("autogenerated", StringComparer.OrdinalIgnoreCase)
                         || function.Flags.Contains("autoprocessed", StringComparer.OrdinalIgnoreCase)
                         || function.Flags.Contains("processed", StringComparer.OrdinalIgnoreCase);

        ScrFunctionOverload? matchedOverload = FindBestOverload(function.Overloads, argTypes);

        if (matchedOverload is null)
        {
            return;
        }

        int idx = 0;
        foreach (ExprNode? argNode in methodCall.Arguments.Arguments)
        {
            if (idx >= matchedOverload.Parameters.Count)
            {
                break;
            }
            ScrFunctionArg param = matchedOverload.Parameters[idx];
            if (param.Type is null || argNode is null)
            {
                idx++;
                continue;
            }

            ScrData expectedType = ScrData.FromApiType(param.Type);
            if (expectedType.IsAny())
            {
                idx++;
                continue;
            }

            // Optional parameters accept undefined (omitted args become undefined in GSC)
            if (param.Mandatory != true)
            {
                expectedType = new ScrData(expectedType.Type | ScrDataTypes.Undefined);
            }

            ScrData actualType = argTypes[idx];
            if (actualType.TypeUnknown())
            {
                idx++;
                continue;
            }

            // IsExactly: see ValidateArgumentTypes — int/number parameters contain the Bool bit.
            if (expectedType.IsExactly(ScrDataTypes.Bool)
                && actualType.IsCompatibleWith(ScrDataTypes.Int)
                && IsIntLiteral01(argNode, out string? replacement))
            {
                AddDiagnostic(argNode.Range, GSCErrorCodes.PreferBooleanLiteral,
                    replacement, argNode is DataExprNode d ? d.Value?.ToString() ?? "0" : "0");
            }

            if (!IsArgumentTypeCompatible(actualType, expectedType))
            {
                GSCErrorCodes code = isUnverified
                    ? GSCErrorCodes.ArgumentTypeMismatchUnverified
                    : GSCErrorCodes.ArgumentTypeMismatch;
                AddDiagnostic(argNode.Range, code,
                    idx + 1, functionName, expectedType.TypeToString(), actualType.TypeToString());
            }
            idx++;
        }
    }

    private ScrData[] AnalyseMethodCallArguments(MethodCallNode methodCall, SymbolTable symbolTable)
    {
        int count = methodCall.Arguments.Arguments.Count;
        ScrData[] types = new ScrData[count];
        int index = 0;
        foreach (ExprNode? argument in methodCall.Arguments.Arguments)
        {
            types[index] = argument is not null
                ? AnalyseExpr(argument, symbolTable, Sense)
                : ScrData.Default;
            index++;
        }
        return types;
    }

    private ScrData AnalyseExpr(ExprNode expr, SymbolTable symbolTable, ParserIntelliSense sense, bool createSenseTokenForRhs = true, bool resultConsumed = true)
    {
        return expr.OperatorType switch
        {
            ExprOperatorType.Binary when expr is NamespacedMemberNode namespaceMember => AnalyseScopeResolution(namespaceMember, symbolTable, sense),
            ExprOperatorType.Binary => AnalyseBinaryExpr((BinaryExprNode)expr, symbolTable, createSenseTokenForRhs),
            ExprOperatorType.Prefix => AnalysePrefixExpr((PrefixExprNode)expr, symbolTable, sense, resultConsumed),
            ExprOperatorType.Postfix => AnalysePostfixExpr((PostfixExprNode)expr, symbolTable, sense),
            ExprOperatorType.DataOperand => AnalyseDataExpr((DataExprNode)expr),
            ExprOperatorType.IdentifierOperand => AnalyseIdentifierExpr((IdentifierExprNode)expr, symbolTable, createSenseTokenForRhs),
            ExprOperatorType.Vector => AnalyseVectorExpr((VectorExprNode)expr, symbolTable),
            ExprOperatorType.Indexer => AnalyseIndexerExpr((ArrayIndexNode)expr, symbolTable),
            ExprOperatorType.CallOn => AnalyseCallOnExpr((CalledOnNode)expr, symbolTable, resultConsumed),
            ExprOperatorType.FunctionCall => AnalyseFunctionCall((FunCallNode)expr, symbolTable, sense),
            ExprOperatorType.Constructor => AnalyseConstructorExpr((ConstructorExprNode)expr, symbolTable),
            ExprOperatorType.Waittill => AnalyseWaittillExpr((WaittillNode)expr, symbolTable, sense),
            ExprOperatorType.WaittillMatch => AnalyseWaittillMatchExpr((WaittillMatchNode)expr, symbolTable, sense),
            ExprOperatorType.Ternary => AnalyseTernaryExpr((TernaryExprNode)expr, symbolTable, sense),
            ExprOperatorType.MethodCall => AnalyseMethodCall((MethodCallNode)expr, symbolTable, sense),
            ExprOperatorType.Deref => AnalyseDeref((DerefExprNode)expr, symbolTable, sense),
            _ => ScrData.Default,
        };
    }

    private ScrData AnalyseWaittillExpr(WaittillNode expr, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData notifyCondition = AnalyseExpr(expr.NotifyCondition, symbolTable, sense);
        ScrData entity = AnalyseExpr(expr.Entity, symbolTable, sense);

        // The called-on must be an entity or struct.
        if (!entity.IsCompatibleWith(ScrDataTypes.Entity | ScrDataTypes.Struct))
        {
            AddDiagnostic(expr.Entity.Range, GSCErrorCodes.NoImplicitConversionExists, entity.TypeToString(), ScrDataTypeNames.Entity);
            return ScrData.Default;
        }

        // The notify condition must be a string or hash.
        if (!notifyCondition.IsCompatibleWith(ScrDataTypes.String | ScrDataTypes.Hash))
        {
            AddDiagnostic(expr.NotifyCondition.Range, GSCErrorCodes.NoImplicitConversionExists, notifyCondition.TypeToString(), ScrDataTypeNames.String, ScrDataTypeNames.Hash);
            return ScrData.Default;
        }

        // Now emit the variables, all as type any.
        foreach (IdentifierExprNode? variable in expr.Variables.Variables)
        {
            if (variable is null)
            {
                continue; // Skip ignored parameters (undefined)
            }

            symbolTable.AddOrSetVariableSymbol(variable.Identifier, ScrData.Default, definitionSource: expr);
            Sense.AddSenseToken(variable.Token, ScrVariableSymbol.Declaration(variable, ScrData.Default));
        }

        // Waittill doesn't return.
        return ScrData.Void;
    }

    private ScrData AnalyseWaittillMatchExpr(WaittillMatchNode expr, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData notifyName = AnalyseExpr(expr.NotifyName, symbolTable, sense);
        ScrData entity = AnalyseExpr(expr.Entity, symbolTable, sense);

        // The called-on must be an entity or struct.
        if (!entity.IsCompatibleWith(ScrDataTypes.Entity | ScrDataTypes.Struct))
        {
            AddDiagnostic(expr.Entity.Range, GSCErrorCodes.NoImplicitConversionExists, entity.TypeToString(), ScrDataTypeNames.Entity);
            return ScrData.Default;
        }

        // The notify name must be a string or hash.
        if (!notifyName.IsCompatibleWith(ScrDataTypes.String | ScrDataTypes.Hash))
        {
            AddDiagnostic(expr.NotifyName.Range, GSCErrorCodes.NoImplicitConversionExists, notifyName.TypeToString(), ScrDataTypeNames.String, ScrDataTypeNames.Hash);
            return ScrData.Default;
        }

        // Analyse optional match value (must be string if provided).
        if (expr.MatchValue is not null)
        {
            ScrData matchValue = AnalyseExpr(expr.MatchValue, symbolTable, sense);
            if (!matchValue.IsCompatibleWith(ScrDataTypes.String | ScrDataTypes.Hash))
            {
                AddDiagnostic(expr.MatchValue.Range, GSCErrorCodes.NoImplicitConversionExists, matchValue.TypeToString(), ScrDataTypeNames.String, ScrDataTypeNames.Hash);
                return ScrData.Default;
            }
        }

        // WaittillMatch doesn't return.
        return ScrData.Void;
    }

    private ScrData AnalyseConstructorExpr(ConstructorExprNode constructor, SymbolTable symbolTable)
    {
        Token classIdentifier = constructor.Identifier;
        string className = classIdentifier.Lexeme;

        if (symbolTable.GlobalSymbolTable.TryGetValue(className, out IExportedSymbol? exportedSymbol) &&
            exportedSymbol is ScrClass scrClass)
        {
            Sense.AddSenseToken(classIdentifier, new ScrClassSymbol(classIdentifier, scrClass));
            return ScrData.Default;
        }

        AddDiagnostic(classIdentifier.Range, GSCErrorCodes.NotDefined, className);
        return ScrData.Default;
    }

    private ScrData AnalyseTernaryExpr(TernaryExprNode ternary, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        // Analyze the condition
        ScrData condition = AnalyseExpr(ternary.Condition, symbolTable, sense);

        // Validate that the condition can be evaluated to a boolean
        if (!condition.TypeUnknown() && !condition.CanEvaluateToBoolean())
        {
            AddDiagnostic(ternary.Condition.Range, GSCErrorCodes.NoImplicitConversionExists, condition.TypeToString(), ScrDataTypeNames.Bool);
        }

        // Check if we can statically determine the result of the condition
        bool? truthy = condition.IsTruthy();

        ScrData trueResult = ScrData.Default;
        if (ternary.Then is not null)
        {
            // If we know the condition is false, we technically don't need to analyze the true branch for values,
            // but we might still want to analyze it for side effects or diagnostics?
            // In DFA, we usually skip unreachable code's effect on flow, but here we are in an expression analyzer.
            // For now, let's analyze both to ensure we catch errors in both branches, but we optimize the return value.
            trueResult = AnalyseExpr(ternary.Then, symbolTable, sense);
        }

        ScrData falseResult = ScrData.Default;
        if (ternary.Else is not null)
        {
            falseResult = AnalyseExpr(ternary.Else, symbolTable, sense);
        }

        // If the condition is known at compile time, return only the taken branch's data
        if (truthy.HasValue)
        {
            return truthy.Value ? trueResult : falseResult;
        }

        // Otherwise, return the merge of both branches
        return ScrData.Merge(trueResult, falseResult);
    }

    private ScrData AnalyseMethodCall(MethodCallNode methodCall, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        // 1. Analyze the target (LHS of ->)
        ScrData target = methodCall.Target is not null
            ? AnalyseExpr(methodCall.Target, symbolTable, sense)
            : new ScrData(ScrDataTypes.Any); // self can be anything

        // 2. Validate target type
        if (!target.IsCompatibleWith(ScrDataTypes.Object))
        {
            AddDiagnostic(methodCall.Target?.Range ?? methodCall.Range,
                GSCErrorCodes.NoImplicitConversionExists,
                target.TypeToString(),
                ScrDataTypeNames.Object);
        }

        // 3. Pre-analyse all arguments (captures types + processes side effects)
        ScrData[] argTypes = AnalyseMethodCallArguments(methodCall, symbolTable);

        // 4. Try to resolve the method from the API
        string methodName = methodCall.Method.Lexeme;
        ScrData functionTarget = symbolTable.TryGetFunction(methodName, out SymbolFlags functionFlags);
        ScrFunction? function = null;

        if (functionTarget.Type != ScrDataTypes.Undefined && functionTarget.TryGetFunction(out function))
        {
            // Add sense token for the method reference
            if (!functionFlags.HasFlag(SymbolFlags.Reserved))
            {
                AddFunctionReferenceToken(methodCall.Method, function, symbolTable);
            }

            // 5. Validate argument count and types
            int argCount = methodCall.Arguments.Arguments.Count;
            ValidateArgumentCount(function, argCount, methodCall.Arguments.Range, methodName, functionFlags);
            ValidateMethodArgumentTypes(function, argTypes, methodCall, methodName, functionFlags);

            // 6. Return the function's return type
            return GetFunctionReturnType(function, functionFlags);
        }

        return ScrData.Default;
    }

    private ScrData AnalyseBinaryExpr(BinaryExprNode binary, SymbolTable symbolTable, bool createSenseTokenForRhs = true)
    {
        if (binary.Operation == TokenType.Dot)
        {
            return AnalyseDotOp(binary, symbolTable, createSenseTokenForRhs, out _);
        }

        if (TryAnalyseAssignmentBinaryExpr(binary, symbolTable, out ScrData assignmentResult))
        {
            return assignmentResult;
        }

        if (IsLogicalBinaryOperator(binary.Operation))
        {
            // NOTE: For now this is behavior-preserving (still analyzes both sides eagerly).
            // This is the hook point for short-circuit evaluation + type narrowing:
            // - AnalyseCondition(...) will return (value, factsWhenTrue, factsWhenFalse)
            // - && / || will analyse RHS under an env refined by LHS facts (reachability-aware)
            // - callers like if/while will apply the returned facts to the then/else environments
            return AnalyseLogicalBinaryExpr(binary, symbolTable);
        }

        ScrData left = AnalyseExpr(binary.Left!, symbolTable, Sense);
        ScrData right = AnalyseExpr(binary.Right!, symbolTable, Sense);

        return binary.Operation switch
        {
            TokenType.Plus => Operators.AnalyseAddOp(binary, left, right),
            TokenType.Minus => Operators.AnalyseMinusOp(binary, left, right),
            TokenType.Multiply => Operators.AnalyseMultiplyOp(binary, left, right),
            TokenType.Divide => Operators.AnalyseDivideOp(binary, left, right),
            TokenType.Modulo => Operators.AnalyseModuloOp(binary, left, right),
            TokenType.BitLeftShift => Operators.AnalyseBitLeftShiftOp(binary, left, right),
            TokenType.BitRightShift => Operators.AnalyseBitRightShiftOp(binary, left, right),
            TokenType.GreaterThan => Operators.AnalyseGreaterThanOp(binary, left, right),
            TokenType.LessThan => Operators.AnalyseLessThanOp(binary, left, right),
            TokenType.GreaterThanEquals => Operators.AnalyseGreaterThanEqualsOp(binary, left, right),
            TokenType.LessThanEquals => Operators.AnalyseLessThanEqualsOp(binary, left, right),
            TokenType.BitAnd => Operators.AnalyseBitAndOp(binary, left, right),
            TokenType.BitOr => Operators.AnalyseBitOrOp(binary, left, right),
            TokenType.BitXor => Operators.AnalyseBitXorOp(binary, left, right),
            TokenType.Equals => Operators.AnalyseEqualsOp(binary, left, right),
            TokenType.NotEquals => Operators.AnalyseNotEqualsOp(binary, left, right),
            TokenType.IdentityEquals => Operators.AnalyseIdentityEqualsOp(binary, left, right),
            TokenType.IdentityNotEquals => Operators.AnalyseIdentityNotEqualsOp(binary, left, right),
            TokenType.And => Operators.AnalyseAndOp(binary, left, right),
            TokenType.Or => Operators.AnalyseOrOp(binary, left, right),
            _ => ScrData.Default,
        };

        // TODO: Binary operators not yet mapped:
        // - Arrow (->)
    }

    private bool TryAnalyseAssignmentBinaryExpr(BinaryExprNode binary, SymbolTable symbolTable, out ScrData result)
    {
        switch (binary.Operation)
        {
            case TokenType.Assign:
                result = AnalyseAssignOp(binary, symbolTable);
                return true;
            case TokenType.PlusAssign:
                result = AnalysePlusAssignOp(binary, symbolTable);
                return true;
            case TokenType.MinusAssign:
            case TokenType.MultiplyAssign:
            case TokenType.DivideAssign:
            case TokenType.ModuloAssign:
            case TokenType.BitAndAssign:
            case TokenType.BitOrAssign:
            case TokenType.BitXorAssign:
            case TokenType.BitLeftShiftAssign:
            case TokenType.BitRightShiftAssign:
                result = AnalyseCompoundAssignOp(binary, symbolTable, binary.Operation);
                return true;
            default:
                result = default;
                return false;
        }
    }

    private ScrData AnalysePrefixExpr(PrefixExprNode prefix, SymbolTable symbolTable, ParserIntelliSense sense, bool resultConsumed = true)
    {
        return prefix.Operation switch
        {
            TokenType.Thread => AnalyseThreadedFunctionCall(prefix, symbolTable, sense, resultConsumed: resultConsumed),
            TokenType.BitAnd => AnalyseFunctionPointer(prefix, symbolTable, sense),
            TokenType.Not => AnalyseNotOp(prefix, symbolTable, sense),
            TokenType.Minus => AnalyseNegationOp(prefix, symbolTable, sense),
            TokenType.BitNot => AnalyseBitwiseNegationOp(prefix, symbolTable, sense),
            _ => ScrData.Default,
        };
    }

    /// <summary>
    /// Analyzes a function pointer expression (e.g., &functionName).
    /// This looks up the function in the global function table and returns a FunctionPointer type.
    /// </summary>
    private ScrData AnalyseFunctionPointer(PrefixExprNode prefix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        // Handle namespaced function pointers (e.g., &util::empty)
        if (prefix.Operand is NamespacedMemberNode namespaced)
        {
            ScrData result = AnalyseScopeResolution(namespaced, symbolTable, sense);
            if (result.Type == ScrDataTypes.Function)
            {
                // Convert Function → FunctionPointer
                if (result.TryGetFunction(out var nsFunc))
                {
                    return ScrData.FunctionPointer(nsFunc);
                }
                return new ScrData(ScrDataTypes.FunctionPointer);
            }
            return result;
        }

        // The operand should be an identifier
        if (prefix.Operand is not IdentifierExprNode identifier)
        {
            // For now, just analyze the operand normally
            return AnalyseExpr(prefix.Operand!, symbolTable, sense);
        }

        // Look up the function in the global function table
        ScrData functionData = symbolTable.TryGetFunction(identifier.Identifier, out SymbolFlags flags);

        if (functionData.Type == ScrDataTypes.Undefined)
        {
            AddDiagnostic(identifier.Range, GSCErrorCodes.FunctionDoesNotExist, identifier.Identifier);
            return ScrData.Undefined();
        }

        if (!functionData.IsCompatibleWith(ScrDataTypes.Function))
        {
            AddDiagnostic(identifier.Range, GSCErrorCodes.ExpectedFunction, functionData.TypeToString());
            return ScrData.Undefined();
        }

        // Add sense token for the function reference
        if (!flags.HasFlag(SymbolFlags.Reserved) && functionData.TryGetFunction(out var func))
        {
            AddFunctionReferenceToken(identifier.Token, func, symbolTable);
            // Return as a FunctionPointer type (a pointer to the function, not the function itself)
            return ScrData.FunctionPointer(func);
        }

        // Return as a FunctionPointer type (a pointer to the function, not the function itself)
        return new ScrData(ScrDataTypes.FunctionPointer);
    }

    private ScrData AnalyseNotOp(PrefixExprNode prefix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData operand = AnalyseExpr(prefix.Operand!, symbolTable, sense);

        // Needs to be a boolean, or at least can be coerced to one.
        if (!operand.IsAny() && !operand.CanEvaluateToBoolean())
        {
            AddDiagnostic(prefix.Operand!.Range, GSCErrorCodes.NoImplicitConversionExists, operand.TypeToString(), ScrDataTypeNames.Bool);
            return ScrData.Default;
        }

        bool? truthy = operand.IsTruthy();

        // Value not known, so just return bool.
        if (truthy is null)
        {
            return new ScrData(ScrDataTypes.Bool);
        }

        return new ScrData(ScrDataTypes.Bool, !truthy.Value);
    }

    private ScrData AnalyseNegationOp(PrefixExprNode prefix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData operand = AnalyseExpr(prefix.Operand!, symbolTable, sense);

        if (operand.TypeUnknown())
        {
            return ScrData.Default;
        }

        if (operand.IsAny())
        {
            return ScrData.Default;
        }

        // Must be a number or vector.
        if (!operand.IsCompatibleWith(ScrDataTypes.Number | ScrDataTypes.Vector))
        {
            AddDiagnostic(prefix.Range, GSCErrorCodes.NoImplicitConversionExists,
                operand.TypeToString(), ScrDataTypeNames.Int, ScrDataTypeNames.Float);
            return ScrData.Default;
        }

        if (operand.Type == ScrDataTypes.Vector)
        {
            return new ScrData(ScrDataTypes.Vector);
        }

        if (operand.Type == ScrDataTypes.Int)
        {
            return new ScrData(ScrDataTypes.Int, booleanValue: operand.BooleanValue);
        }

        // If it's not int or vector, then it's a float.
        return new ScrData(ScrDataTypes.Float);
    }

    private ScrData AnalyseBitwiseNegationOp(PrefixExprNode prefix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData operand = AnalyseExpr(prefix.Operand!, symbolTable, sense);

        if (operand.TypeUnknown())
        {
            return ScrData.Default;
        }

        if (operand.IsAny())
        {
            return ScrData.Default;
        }

        if (!operand.IsCompatibleWith(ScrDataTypes.Int))
        {
            AddDiagnostic(prefix.Range, GSCErrorCodes.NoImplicitConversionExists,
                operand.TypeToString(), ScrDataTypeNames.Int);
            return ScrData.Default;
        }

        return new ScrData(ScrDataTypes.Int, booleanValue: null);
    }

    private ScrData AnalysePostfixExpr(PostfixExprNode postfix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        return postfix.Operation switch
        {
            TokenType.Increment => AnalysePostIncrementOp(postfix, symbolTable, sense),
            TokenType.Decrement => AnalysePostDecrementOp(postfix, symbolTable, sense),
            _ => ScrData.Default,
        };
    }

    /// <summary>
    /// Helper method to perform assignment to either a local variable or a struct property.
    /// Handles read-only validation, symbol table updates, and sense token generation.
    /// </summary>
    /// <param name="operand">The expression node representing the assignment target (identifier or dot expression)</param>
    /// <param name="target">The analyzed ScrData of the target before assignment</param>
    /// <param name="newValue">The new value to assign</param>
    /// <param name="symbolTable">The symbol table to update</param>
    /// <returns>True if assignment was successful, false if it failed (e.g., read-only)</returns>
    private bool TryAssignToTarget(ExprNode operand, ScrData target, ScrData newValue, SymbolTable symbolTable)
    {
        // Assigning to a local variable
        if (operand is IdentifierExprNode identifier)
        {
            string symbolName = identifier.Identifier;

            // Check if the symbol is a constant (tracked via symbol table, not ScrData.ReadOnly)
            if (symbolTable.SymbolIsConstant(symbolName))
            {
                AddDiagnostic(identifier.Range, GSCErrorCodes.CannotAssignToConstant, symbolName);
                return false;
            }

            AstNode? defSource = symbolTable.TryGetLocalVariableInfo(symbolName)?.DefinitionSource;
            symbolTable.SetSymbol(symbolName, newValue);
            Sense.AddSenseToken(identifier.Token, ScrVariableSymbol.Usage(identifier, newValue, definitionSource: defSource));
            return true;
        }

        // Assigning to a property on a struct/entity/object - use AnalyseDotOp to get the owner
        if (operand is BinaryExprNode binaryExprNode && binaryExprNode.Operation == TokenType.Dot)
        {
            ScrData dotResult = AnalyseDotOp(binaryExprNode, symbolTable, false, out ScrData owner);
            string fieldName = dotResult.FieldName ?? throw new NullReferenceException("Sanity check failed: Dot result has no field name.");

            if (!TryAssignField(binaryExprNode, owner, fieldName, newValue))
            {
                return false;
            }

            if (binaryExprNode.Right is IdentifierExprNode identifierNode)
            {
                bool isClassMember = symbolTable.CurrentClass is not null &&
                    symbolTable.CurrentClass.Members.Any(m => m.Name.Equals(fieldName, StringComparison.OrdinalIgnoreCase));

                if (isClassMember)
                {
                    Sense.AddSenseToken(identifierNode.Token, new ScrClassPropertySymbol(identifierNode, newValue, symbolTable.CurrentClass!));
                }
                else
                {
                    Sense.AddSenseToken(identifierNode.Token, new ScrFieldSymbol(identifierNode, newValue));
                }
            }

            return true;
        }

        // Unsupported assignment target
        return false;
    }

    private bool TryAssignField(BinaryExprNode dotExpr, ScrData owner, string fieldName, ScrData value)
    {
        bool success = owner.TrySetField(fieldName, value, out ScrSetFieldFailure? failure);
        if (success)
        {
            return true;
        }

        if (failure is null)
        {
            AddDiagnostic(dotExpr.Range, GSCErrorCodes.InvalidAssignmentTarget);
            return false;
        }

        if (failure.Value.IncompatibleBaseTypes is ScrDataTypes incompatibleBaseTypes)
        {
            AddDiagnostic(dotExpr.Range, GSCErrorCodes.DoesNotContainMember, fieldName, ScrDataTypeNames.TypeToString(incompatibleBaseTypes));
            return false;
        }

        // Check for array/string size readonly first (it can exist alongside entity failures)
        bool anyReadOnly = failure.Value.SizeFieldReadOnly;

        if (failure.Value.EntityFailures is { } entityFailures)
        {
            // Single pass: collect flags + any extra info we may want for the chosen diagnostic.
            // We intentionally emit ONE diagnostic (highest priority) to avoid spam and repeated passes.
            bool anyImmutable = false;
            bool anyTypeMismatch = false;
            HashSet<ScrEntityTypes>? immutableEntityTypes = null;
            ScrDataTypes expectedForMismatch = ScrDataTypes.Void;

            foreach (ScrEntitySetFieldFailureInfo fail in entityFailures)
            {
                switch (fail.Reason)
                {
                    case ScrEntitySetFieldResult.EntityImmutable:
                        anyImmutable = true;
                        immutableEntityTypes ??= new HashSet<ScrEntityTypes>();
                        immutableEntityTypes.Add(fail.EntityType);
                        break;
                    case ScrEntitySetFieldResult.FieldReadOnly:
                        anyReadOnly = true;
                        break;
                    case ScrEntitySetFieldResult.FieldTypeMismatch:
                        anyTypeMismatch = true;
                        expectedForMismatch |= ScrEntityRegistry.GetField(fail.EntityType, fieldName).Type;
                        break;
                }
            }

            // Prefer a single, high-signal diagnostic.
            // Priority (most actionable first):
            // 1) Immutable entity (can't ever work)
            // 2) Readonly property (can't ever work)
            // 3) Type mismatch (might work with cast/change)
            if (anyImmutable)
            {
                string immutableTypes = immutableEntityTypes is null || immutableEntityTypes.Count == 0
                    ? ScrDataTypeNames.Entity
                    : string.Join(" | ", immutableEntityTypes.Select(ScrEntityTypeNames.TypeToString));

                AddDiagnostic(dotExpr.Range, GSCErrorCodes.CannotAssignToImmutableEntity, immutableTypes);
                return false;
            }

            if (anyReadOnly)
            {
                AddDiagnostic(dotExpr.Right!.Range, GSCErrorCodes.CannotAssignToReadOnlyProperty, fieldName);
                return false;
            }

            if (anyTypeMismatch)
            {
                string expectedType = expectedForMismatch == ScrDataTypes.Void
                    ? ScrDataTypeNames.Any
                    : ScrDataTypeNames.TypeToString(expectedForMismatch);

                AddDiagnostic(dotExpr.Right!.Range, GSCErrorCodes.PredefinedFieldTypeMismatch, value.TypeToString(), expectedType);
                return false;
            }
        }
        // Handle array/string size readonly when there are no entity failures
        else if (anyReadOnly)
        {
            AddDiagnostic(dotExpr.Right!.Range, GSCErrorCodes.CannotAssignToReadOnlyProperty, fieldName);
            return false;
        }

        AddDiagnostic(dotExpr.Range, GSCErrorCodes.InvalidAssignmentTarget);
        return false;
    }

    private ScrData AnalysePostIncrementOp(PostfixExprNode postfix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData target = AnalyseExpr(postfix.Operand!, symbolTable, sense, false);

        // Must be an int or float.
        if (!target.IsCompatibleWith(ScrDataTypes.Int) && !target.IsCompatibleWith(ScrDataTypes.Float))
        {
            AddDiagnostic(postfix.Operand!.Range, GSCErrorCodes.NoImplicitConversionExists, target.TypeToString(), ScrDataTypeNames.Int);
            return ScrData.Default;
        }

        // Perform the assignment using the shared helper
        if (!TryAssignToTarget(postfix.Operand!, target, new ScrData(target.Type), symbolTable))
        {
            return ScrData.Default;
        }

        // Return its old value (post-increment returns the value before incrementing)
        return target;
    }

    private ScrData AnalysePostDecrementOp(PostfixExprNode postfix, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        ScrData target = AnalyseExpr(postfix.Operand!, symbolTable, sense, false);

        // Must be an int or float.
        if (!target.IsCompatibleWith(ScrDataTypes.Int) && !target.IsCompatibleWith(ScrDataTypes.Float))
        {
            AddDiagnostic(postfix.Operand!.Range, GSCErrorCodes.NoImplicitConversionExists, target.TypeToString(), ScrDataTypeNames.Int);
            return ScrData.Default;
        }

        // Perform the assignment using the shared helper
        if (!TryAssignToTarget(postfix.Operand!, target, new ScrData(target.Type), symbolTable))
        {
            return ScrData.Default;
        }

        // Return its old value (post-decrement returns the value before decrementing)
        return target;
    }

    private ScrData AnalyseAssignOp(BinaryExprNode node, SymbolTable symbolTable)
    {
        ScrData right = AnalyseExpr(node.Right!, symbolTable, Sense);

        // If left is a dot expression, analyse it directly so we can get trace of the owner.
        if (node.Left is BinaryExprNode binaryExprNode && binaryExprNode.Operation == TokenType.Dot)
        {
            ScrData dotLeft = AnalyseDotOp(binaryExprNode, symbolTable, false, out ScrData leftOwner);
            string fieldName = dotLeft.FieldName ?? throw new NullReferenceException("Sanity check failed: Dot result has no field name.");

            if (!TryAssignField(binaryExprNode, leftOwner, fieldName, right))
            {
                return ScrData.Default;
            }

            // Success - emit the sense token.
            IdentifierExprNode identifierNode = (IdentifierExprNode)binaryExprNode.Right!;
            Sense.AddSenseToken(identifierNode.Token, new ScrFieldSymbol(identifierNode, right));

            return right;
        }

        // Otherwise, any other type of assignment.
        ScrData left = AnalyseExpr(node.Left!, symbolTable, Sense, false);

        // Assigning to a local variable or class member
        if (node.Left is IdentifierExprNode identifier)
        {
            string symbolName = identifier.Identifier;

            // Check if this is a class member being assigned
            bool isClassMember = symbolTable.CurrentClass is not null &&
                symbolTable.IsMemberInClassHierarchy(symbolTable.CurrentClass, symbolName);

            if (isClassMember)
            {
                // Assigning to a class member (implicit this.member)
                Sense.AddSenseToken(identifier.Token, new ScrClassPropertySymbol(identifier, right, symbolTable.CurrentClass!));
                return right;
            }

            // Check if the symbol is a constant (tracked via symbol table, not ScrData.ReadOnly)
            if (symbolTable.SymbolIsConstant(symbolName))
            {
                AddDiagnostic(identifier.Range, GSCErrorCodes.CannotAssignToConstant, symbolName);
                return ScrData.Default;
            }

            if (right.Type == ScrDataTypes.Function)
            {
                AddDiagnostic(node.Right!.Range, GSCErrorCodes.StoreFunctionAsPointer);
                return ScrData.Default;
            }

            AssignmentResult assignmentResult = symbolTable.AddOrSetVariableSymbol(symbolName, right with { ReadOnly = false }, definitionSource: node);

            // Failed, because the symbol is a constant
            if (assignmentResult == AssignmentResult.FailedConstant)
            {
                AddDiagnostic(identifier.Range, GSCErrorCodes.CannotAssignToConstant, symbolName);
                return ScrData.Default;
            }

            // Failed, because the symbol is reserved
            if (assignmentResult == AssignmentResult.FailedReserved)
            {
                AddDiagnostic(identifier.Range, GSCErrorCodes.ReservedSymbol, symbolName);
                return ScrData.Default;
            }

            if (assignmentResult == AssignmentResult.SuccessNew)
            {
                Sense.AddSenseToken(identifier.Token, ScrVariableSymbol.Declaration(identifier, right));
                return right;
            }

            AstNode? defSource = symbolTable.TryGetLocalVariableInfo(symbolName)?.DefinitionSource;
            Sense.AddSenseToken(identifier.Token, ScrVariableSymbol.Usage(identifier, right, definitionSource: defSource));
            return right;
        }

        // NOTE: Dot expressions are handled at the top of this method via AnalyseDotOp

        // TODO: once all cases are covered, we should enable this.
        // sense.AddSpaDiagnostic(node.Left!.Range, GSCErrorCodes.InvalidAssignmentTarget);
        return ScrData.Default;
    }

    private ScrData AnalyseCompoundAssignOp(BinaryExprNode node, SymbolTable symbolTable, TokenType op)
    {
        // Evaluate LHS without creating a RHS usage token, and RHS normally
        ScrData left = AnalyseExpr(node.Left!, symbolTable, Sense, false);
        ScrData right = AnalyseExpr(node.Right!, symbolTable, Sense);

        // For compound assignments on identifiers, ensure the variable or class member exists
        if (node.Left is IdentifierExprNode identifier)
        {
            bool isClassMember = symbolTable.CurrentClass is not null &&
                symbolTable.IsMemberInClassHierarchy(symbolTable.CurrentClass, identifier.Identifier);

            if (isClassMember)
            {
                Sense.AddSenseToken(identifier.Token, new ScrClassPropertySymbol(identifier, left, symbolTable.CurrentClass!));
            }
            else if (!symbolTable.ContainsSymbol(identifier.Identifier))
            {
                AddDiagnostic(identifier.Range, GSCErrorCodes.NotDefined, identifier.Identifier);
                return ScrData.Default;
            }
        }

        // Compute the result of the compound operation
        ScrData result = Operators.ExecuteCompoundOp(op, node, left, right);

        // Perform the assignment using the shared helper
        if (!TryAssignToTarget(node.Left!, left, result, symbolTable))
        {
            return ScrData.Default;
        }

        return result;
    }

    private ScrData AnalysePlusAssignOp(BinaryExprNode node, SymbolTable symbolTable)
    {
        return AnalyseCompoundAssignOp(node, symbolTable, TokenType.PlusAssign);
    }

    private ScrData AnalyseDotOp(BinaryExprNode node, SymbolTable symbolTable, bool createSenseTokenForField, out ScrData owner)
    {
        owner = ScrData.Default;

        if (node.Right!.OperatorType != ExprOperatorType.IdentifierOperand || node.Right is not IdentifierExprNode identifierNode)
        {

            AddDiagnostic(node.Right!.Range, GSCErrorCodes.IdentifierExpected);
            return ScrData.Default;
        }

        ScrData left = AnalyseExpr(node.Left!, symbolTable, Sense);
        owner = left;

        ScrData result = left.TryGetField(identifierNode.Identifier, out ScrDataTypes? incompatibleTypes);

        if(result == ScrData.Void)
        {
            AddDiagnostic(node.Range, GSCErrorCodes.DoesNotContainMember, identifierNode.Identifier, ScrDataTypeNames.TypeToString(incompatibleTypes!.Value));
            // FieldName is already set by TryGetField, return a default with it preserved
            ScrData errorResult = ScrData.Default;
            errorResult.FieldName = identifierNode.Identifier;
            return errorResult;
        }

        bool isClassMember = symbolTable.CurrentClass is not null &&
            symbolTable.IsMemberInClassHierarchy(symbolTable.CurrentClass, identifierNode.Identifier);

        // Emit sense tokens for the field.
        if (createSenseTokenForField)
        {
            if (isClassMember)
            {
                Sense.AddSenseToken(identifierNode.Token, new ScrClassPropertySymbol(identifierNode, result, symbolTable.CurrentClass!, isReadOnly: result.ReadOnly));
            }
            else
            {
                Sense.AddSenseToken(identifierNode.Token, new ScrFieldSymbol(identifierNode, result, isReadOnly: result.ReadOnly));
            }
        }

        return result;
    }

    private ScrData AnalyseDataExpr(DataExprNode expr)
    {
        return ScrData.FromDataExprNode(expr);
    }

    private ScrData AnalyseIdentifierExpr(IdentifierExprNode expr, SymbolTable symbolTable, bool createSenseTokenForRhs = true)
    {
        // Animation references (%identifier) are anim type
        if (expr.IsAnim)
        {
            return new ScrData(ScrDataTypes.Anim);
        }

        // Check if this identifier is a class member (before checking local variables)
        if (symbolTable.CurrentClass is not null)
        {
            bool isClassMember = symbolTable.IsMemberInClassHierarchy(symbolTable.CurrentClass, expr.Identifier);

            if (isClassMember)
            {
                // This is an implicit reference to a class member (like accessing this.member)
                if (createSenseTokenForRhs)
                {
                    Sense.AddSenseToken(expr.Token, new ScrClassPropertySymbol(expr, ScrData.Default, symbolTable.CurrentClass));
                }
                // Return a default type since we don't track member values without explicit self reference
                return ScrData.Default;
            }
        }

        // Analyze and return the corresponding ScrData for the local variable
        ScrData? value = symbolTable.TryGetLocalVariable(expr.Identifier, out SymbolFlags flags);
        if (value is not ScrData data)
        {
            return ScrData.Undefined();
        }

        if (flags.HasFlag(SymbolFlags.Global))
        {
            if (createSenseTokenForRhs)
            {
                Sense.AddSenseToken(expr.Token, ScrVariableSymbol.LanguageSymbol(expr, data));
            }
            return data;
        }

        if (createSenseTokenForRhs)
        {
            bool isConstant = symbolTable.SymbolIsConstant(expr.Identifier);
            AstNode? defSource = symbolTable.TryGetLocalVariableInfo(expr.Identifier)?.DefinitionSource;
            Sense.AddSenseToken(expr.Token, ScrVariableSymbol.Usage(expr, data, isConstant, defSource));
        }
        return data;
    }

    private ScrData AnalyseVectorExpr(VectorExprNode expr, SymbolTable symbolTable)
    {
        if (expr.Y is null || expr.Z is null)
        {
            return ScrData.Default;
        }

        ScrData x = AnalyseExpr(expr.X, symbolTable, Sense);
        ScrData y = AnalyseExpr(expr.Y, symbolTable, Sense);
        ScrData z = AnalyseExpr(expr.Z, symbolTable, Sense);

        if (x.TypeUnknown() || y.TypeUnknown() || z.TypeUnknown())
        {
            return new ScrData(ScrDataTypes.Vector);
        }

        if (!x.IsCompatibleWith(ScrDataTypes.Number))
        {
            AddDiagnostic(expr.X!.Range, GSCErrorCodes.InvalidVectorComponent, x.TypeToString());
            return ScrData.Default;
        }
        if (!y.IsCompatibleWith(ScrDataTypes.Number))
        {
            AddDiagnostic(expr.Y!.Range, GSCErrorCodes.InvalidVectorComponent, y.TypeToString());
            return ScrData.Default;
        }
        if (!z.IsCompatibleWith(ScrDataTypes.Number))
        {
            AddDiagnostic(expr.Z!.Range, GSCErrorCodes.InvalidVectorComponent, z.TypeToString());
            return ScrData.Default;
        }

        return new ScrData(ScrDataTypes.Vector);
    }

    private ScrData AnalyseIndexerExpr(ArrayIndexNode expr, SymbolTable symbolTable)
    {
        ScrData collection = AnalyseExpr(expr.Array, symbolTable, Sense);

        if (expr.Index is null)
        {
            return ScrData.Default;
        }

        ScrData indexer = AnalyseExpr(expr.Index, symbolTable, Sense);

        if (indexer.TypeUnknown())
        {
            return ScrData.Default;
        }

        // We might not know which collection type it is, but it won't be indexable.
        if (collection.TypeUnknown())
        {
            if (!indexer.IsArrayIndexer())
            {
                AddDiagnostic(expr.Index!.Range, GSCErrorCodes.CannotUseAsIndexer, indexer.TypeToString());
            }
            return ScrData.Default;
        }

        // Arrays aren't strongly typed (right now), so we can just return default.
        if (collection.Type == ScrDataTypes.Array)
        {
            if (!indexer.IsArrayIndexer())
            {
                AddDiagnostic(expr.Index!.Range, GSCErrorCodes.CannotUseAsIndexer, indexer.TypeToString());
                return ScrData.Default;
            }

            return ScrData.Default;
        }

        return ScrData.Default;
    }

    private ScrData AnalyseCallOnExpr(CalledOnNode expr, SymbolTable symbolTable, bool resultConsumed = true)
    {
        ScrData target = AnalyseExpr(expr.On, symbolTable, Sense);

        return AnalyseCall(expr.Call, symbolTable, Sense, target, resultConsumed);
    }

    private ScrData AnalyseCall(ExprNode call, SymbolTable symbolTable, ParserIntelliSense sense, ScrData? target = null, bool resultConsumed = true)
    {
        // If target is null, we don't know, just use any.
        ScrData targetValue = target ?? ScrData.Default;

        // Analyse the call.
        return call.OperatorType switch
        {
            ExprOperatorType.FunctionCall => AnalyseFunctionCall((FunCallNode)call, symbolTable, sense, targetValue),
            ExprOperatorType.Prefix when call is PrefixExprNode prefix && prefix.Operation == TokenType.Thread => AnalyseThreadedFunctionCall(prefix, symbolTable, sense, targetValue, resultConsumed),
            ExprOperatorType.Binary when call is NamespacedMemberNode namespaced => AnalyseScopeResolution(namespaced, symbolTable, sense, targetValue),
            // for now... might be an error later.
            _ => ScrData.Default
        };
    }

    private ScrData AnalyseScopeResolution(NamespacedMemberNode namespaced, SymbolTable symbolTable, ParserIntelliSense sense, ScrData? target = null)
    {
        return AnalyseScopeResolution(namespaced, symbolTable, sense, out _, target);
    }

    private ScrData AnalyseScopeResolution(NamespacedMemberNode namespaced, SymbolTable symbolTable, ParserIntelliSense sense, out SymbolFlags outFlags, ScrData? target = null)
    {
        outFlags = SymbolFlags.None;
        ScrData targetValue = target ?? ScrData.Default;

        // I'm pretty sure the grammar stops this from happening, but no harm in being sure.
        if (namespaced.Namespace is not IdentifierExprNode namespaceNode)
        {
            AddDiagnostic(namespaced.Namespace.Range, GSCErrorCodes.IdentifierExpected);
            return ScrData.Default;
        }

        // Emit the namespace symbol.
        Sense.AddSenseToken(namespaceNode.Token, new ScrNamespaceScopeSymbol(namespaceNode));

        // Now find what symbol within the namespace we're targeting.
        // Again - probably not necessary, but no harm in being sure.
        if (namespaced.Member is not IdentifierExprNode memberNode)
        {
            AddDiagnostic(namespaced.Member!.Range, GSCErrorCodes.IdentifierExpected);
            return ScrData.Default;
        }

        ScrData symbol = symbolTable.TryGetNamespacedFunctionSymbol(namespaceNode.Identifier, memberNode.Identifier, out SymbolFlags flags, out bool namespaceExists);
        outFlags = flags;

        // Validate that the namespace exists
        if (!namespaceExists)
        {
            AddDiagnostic(namespaceNode.Range, GSCErrorCodes.UnknownNamespace, namespaceNode.Identifier);
            return ScrData.Default;
        }

        // Namespace is known but the requested function was not found inside it.
        // Return ScrData.Default (type-unknown) so the upstream call-site check does
        // not emit a cascading ExpectedFunction (3036) error — that message
        // ("expected a function, got 'undefined'") is meaningless when the whole line
        // is syntactically valid and the only problem is a missing symbol.
        if (symbol.Type == ScrDataTypes.Undefined)
        {
            AddDiagnostic(memberNode.Range, GSCErrorCodes.NamespaceDoesNotContainFunction,
                namespaceNode.Identifier, memberNode.Identifier);
            return ScrData.Default;
        }

        if (flags.HasFlag(SymbolFlags.Global) && symbol.Type == ScrDataTypes.Function)
        {
            if (symbol.TryGetFunction(out ScrFunction? function))
            {
                // Check if the namespace is a class
                if (symbolTable.GlobalSymbolTable.TryGetValue(namespaceNode.Identifier, out IExportedSymbol? classSymbol)
                    && classSymbol.Type == ExportedSymbolType.Class)
                {
                    ScrClass scrClass = (ScrClass)classSymbol;
                    Sense.AddSenseToken(memberNode.Token, new ScrMethodReferenceSymbol(memberNode.Token, function, scrClass));
                }
                else
                {
                    Sense.AddSenseToken(memberNode.Token, new ScrFunctionReferenceSymbol(memberNode.Token, function));
                }
            }
        }

        return symbol;
    }

    /// <summary>
    /// Analyzes a dereference operation [[ expr ]], validating that expr is a FunctionPointer
    /// and converting it to a Function type for calling.
    /// </summary>
    private ScrData AnalyseDeref(DerefExprNode deref, SymbolTable symbolTable, ParserIntelliSense sense)
    {
        // Analyze the expression inside the dereference brackets
        ScrData innerData = AnalyseExpr(deref.Inner, symbolTable, sense);

        // If type is unknown, we can't validate
        if (innerData.TypeUnknown())
        {
            return ScrData.Default;
        }

        // Dereference: FunctionPointer → Function
        if (innerData.Type == ScrDataTypes.FunctionPointer)
        {
            if (innerData.TryGetFunction(out var func))
            {
                return ScrData.Function(func);
            }
            return new ScrData(ScrDataTypes.Function);
        }

        // For other types (e.g., object/class pointers used with [[ ptr ]]->method()),
        // pass through — the caller validates the resulting type.
        return innerData;
    }

    private ScrData AnalyseFunctionCall(FunCallNode call, SymbolTable symbolTable, ParserIntelliSense sense, ScrData? target = null)
    {
        ScrData targetValue = target ?? ScrData.Default;

        // Get the function we're targeting.
        if (call.Function is null)
        {
            return ScrData.Default;
        }

        ScrData functionTarget;
        SymbolFlags functionFlags = SymbolFlags.None;

        // Dereference call [[ expr ]]() - look up the inner expression as a local variable
        if (call.Function is DerefExprNode derefNode)
        {
            functionTarget = AnalyseDeref(derefNode, symbolTable, sense);
            functionFlags = SymbolFlags.None;
        }
        // Direct identifier call foo() - look up in global function table
        else if (call.Function is IdentifierExprNode identifierNode)
        {
            // Pass argument count to enable signature-based fallback to API functions
            int argumentCount = call.Arguments?.Arguments?.Count ?? 0;
            functionTarget = symbolTable.TryGetFunction(identifierNode.Identifier, out functionFlags, argumentCount);

            if (functionTarget.Type == ScrDataTypes.Undefined)
            {
                AddDiagnostic(call.Function.Range, GSCErrorCodes.FunctionDoesNotExist, identifierNode.Identifier);
                return ScrData.Default;
            }

            // Add sense token for the function reference
            if (!functionFlags.HasFlag(SymbolFlags.Reserved) && functionTarget.TryGetFunction(out var func))
            {
                AddFunctionReferenceToken(identifierNode.Token, func, symbolTable);
            }
        }
        // Namespaced function call namespace::func() - analyze as scope resolution
        else if (call.Function is NamespacedMemberNode namespacedMember)
        {
            functionTarget = AnalyseScopeResolution(namespacedMember, symbolTable, sense, out functionFlags);
        }
        else
        {
            // Other complex expressions - analyze directly
            functionTarget = AnalyseExpr(call.Function, symbolTable, sense);
            functionFlags = SymbolFlags.None;
        }

        if (!functionTarget.IsCompatibleWith(ScrDataTypes.Function))
        {
            if (!functionTarget.TypeUnknown())
            {
                AddDiagnostic(call.Function!.Range, GSCErrorCodes.ExpectedFunction, functionTarget.TypeToString());
            }
            return ScrData.Default;
        }

        functionTarget.TryGetFunction(out ScrFunction? function);

        // Pre-analyse all arguments.
        ScrData[] argTypes = AnalyseCallArguments(call, symbolTable);

        // Check for emulated function behavior (type guards, custom validation, etc.)
        if (functionFlags.HasFlag(SymbolFlags.Reserved) || functionFlags.HasFlag(SymbolFlags.BuiltIn))
        {
            string? emulatedName = call.Function is IdentifierExprNode emulatedId ? emulatedId.Identifier : null;
            if (emulatedName is not null
                && EmulatedFunctionRegistry.TryGet(emulatedName, out EmulatedFunction? emulated)
                && emulated.EmulateCall is not null)
            {
                EmulationContext ctx = new()
                {
                    Call = call,
                    ArgumentTypes = argTypes,
                    Target = target,
                    Silent = Silent,
                    Sense = Sense
                };
                return emulated.EmulateCall(in ctx);
            }
        }

        // Validate argument count
        int argCount = call.Arguments.Arguments.Count;
        string functionName = call.Function is IdentifierExprNode idNode ? idNode.Identifier :
                             call.Function is NamespacedMemberNode nmNode && nmNode.Member is IdentifierExprNode memberId ? memberId.Identifier :
                             function?.Name ?? "<unknown>";
        ValidateArgumentCount(function, argCount, call.Arguments.Range, functionName, functionFlags);
        ValidateArgumentTypes(function, argTypes, call, functionName, functionFlags);

        // Check if a devblock-only function is being used outside a devblock
        if (!Flags.InDevBlock
            && function is not null
            && function.Flags.Contains("devblock", StringComparer.OrdinalIgnoreCase))
        {
            AddDiagnostic(call.Function!.Range, GSCErrorCodes.DevBlockFunctionOutsideDevBlock, functionName);
        }

        WarnIfBrokenFunctionUsed(call.Function!.Range, function, functionName);

        // Return the function's return type if known
        return GetFunctionReturnType(function, functionFlags);
    }

    /// <summary>
    /// Gets the return type of a function from its API specification.
    /// </summary>
    internal static ScrData GetFunctionReturnType(ScrFunction? function, SymbolFlags flags = SymbolFlags.None)
    {
        if (function is null)
        {
            return ScrData.Default;
        }

        // Get the first overload's return type (TODO: handle multiple overloads)
        if (function.Overloads.Count == 0)
        {
            return ScrData.Default;
        }

        ScrFunctionReturn? returnSpec = function.Overloads[0].Returns;

        // If explicitly void, return void
        if (returnSpec?.Void == true)
        {
            return ScrData.Void;
        }

        // Convert the API return type to ScrData
        ScrData returnType = ScrData.FromApiType(returnSpec?.Type);

        if (flags.HasFlag(SymbolFlags.BuiltIn))
        {
            returnType = returnType.Copy() with { Indeterminate = true };
        }

        return returnType;
    }

    private ScrData AnalyseThreadedFunctionCall(PrefixExprNode call, SymbolTable symbolTable, ParserIntelliSense sense, ScrData? target = null, bool resultConsumed = true)
    {
        ScrData targetValue = target ?? ScrData.Default;

        if (call.Operand is null)
        {
            return ScrData.Undefined();
        }

        ScrData functionTarget;
        FunCallNode? functionCall = null;

        // If it's a direct identifier, look it up in the global function table
        if (call.Operand is IdentifierExprNode identifierNode)
        {
            functionTarget = symbolTable.TryGetFunction(identifierNode.Identifier, out SymbolFlags flags);

            if (functionTarget.Type == ScrDataTypes.Undefined)
            {
                AddDiagnostic(call.Operand.Range, GSCErrorCodes.FunctionDoesNotExist, identifierNode.Identifier);
                return ScrData.Undefined();
            }

            // Add sense token for the function reference
            if (!flags.HasFlag(SymbolFlags.Reserved) && functionTarget.TryGetFunction(out var func))
            {
                AddFunctionReferenceToken(identifierNode.Token, func, symbolTable);
            }
        }
        // If it's a namespaced function, analyze it as scope resolution
        // This handles: thread namespace::func() - direct global function call
        else if (call.Operand is NamespacedMemberNode namespacedMember)
        {
            functionTarget = AnalyseScopeResolution(namespacedMember, symbolTable, sense);
        }
        // If it's a function call node, analyze it and extract the function being called
        else if (call.Operand is FunCallNode funCall)
        {
            functionCall = funCall;
            // Recursively analyze the function call to get the target
            functionTarget = AnalyseFunctionCall(funCall, symbolTable, sense, targetValue);
        }
        // Dereference call thread [[ expr ]]() - look up the inner expression as a local variable
        else if (call.Operand is DerefExprNode derefNode)
        {
            functionTarget = AnalyseDeref(derefNode, symbolTable, sense);
        }
        else
        {
            // Other complex expressions - analyze directly
            functionTarget = AnalyseExpr(call.Operand, symbolTable, sense);
        }

        // Verify it's actually a function
        if (!functionTarget.IsCompatibleWith(ScrDataTypes.Function))
        {
            AddDiagnostic(call.Operand.Range, GSCErrorCodes.ExpectedFunction, functionTarget.TypeToString());
        }

        // TODO: Validate argument count for threaded calls (if not already handled by recursive call)

        functionTarget.TryGetFunction(out ScrFunction? function);
        string functionName = function?.Name ?? "<unknown>";
        WarnIfBrokenFunctionUsed(call.Operand.Range, function, functionName);

        if (resultConsumed)
        {
            AddDiagnostic(call.Range, GSCErrorCodes.ConsumedThreadedCallResult);
        }

        // Treat the result as dynamic so downstream analysis can continue,
        // but warn when callers rely on it because a blocking thread can yield undefined.
        return ScrData.Default;
    }
}
