using GSCode.Data.Models.Interfaces;
using Newtonsoft.Json;

namespace GSCode.Data.Models;

public partial record class ScrFunction : IExportedSymbol
{
    /// <summary>The name of the function.</summary>
    [JsonRequired]
    public required string Name { get; set; }

    /// <summary>The description for this function.</summary>
    public string? Description { get; set; }

    /// <summary>An example of this function's usage.</summary>
    public string? Example { get; set; }

    /// <summary>The documentation comment for this function (user-defined scripts only).</summary>
    public string? DocComment { get; set; }

    /// <summary>The overloads (variants) of this function.</summary>
    public List<ScrFunctionOverload> Overloads { get; set; } = [];

    /// <summary>The flags list of this function, which may be empty.</summary>
    public List<string> Flags { get; set; } = [];

    /// <summary>The namespace of this function.</summary>
    public string Namespace { get; set; } = "sys";

    public ExportedSymbolType Type { get; set; } = ExportedSymbolType.Function;

    /// <summary>
    /// Whether this function's namespace can be omitted at call-sites.
    /// True for built-in API functions (sys namespace) and functions in the current script's namespace.
    /// </summary>
    public bool Implicit { get; set; } = false;

    /// <summary>Whether this function is private and cannot be accessed from other scripts.</summary>
    public bool Private { get; set; } = false;

    /// <summary>
    /// Whether this function is a built-in API function (loaded from the code API JSON).
    /// Built-in functions are marked with the "autogenerated" flag.
    /// All built-in functions are <see cref="Implicit"/>, but not all Implicit functions are built-in.
    /// </summary>
    public bool IsBuiltIn => Flags.Contains("autogenerated", StringComparer.OrdinalIgnoreCase);
}

