import type {
	ScrDataType,
	ScrFunction,
	ScrFunctionOverload,
	ScrFunctionParameter,
	ScrReturnValue
} from '$lib/models/library';
import { validateFunction } from './validation';

/**
 * Wraps an individual function with editor state and validation.
 */
export class FunctionEditor {
	function: ScrFunction = $state() as any;
	private readonly _originalFunction: string;

	/** Whether this function was newly created in this session (not in original library) */
	readonly isNew: boolean;

	/** Whether this function is marked for deletion (soft-delete) */
	deleted = $state(false);

	/**
	 * Tracks whether this function has been mutated via editor methods.
	 * Much cheaper than JSON.stringify comparison for bulk stats computation.
	 */
	private _dirty = $state(false);

	/** Whether this function has been edited (cheap check via dirty flag) */
	readonly edited = $derived(this.deleted || this._dirty);

	/**
	 * Whether this function has actually changed from its original state.
	 * Uses JSON.stringify comparison — only call this for individual functions, not in bulk loops.
	 */
	hasActualChanges(): boolean {
		if (this.deleted) return true;
		if (!this.function || !this._originalFunction) return false;
		return JSON.stringify(this.function) !== this._originalFunction;
	}

	/** List of validation error messages for this function */
	readonly validationErrors = $derived(validateFunction(this.function));

	/** Whether this function's definition passes validation */
	readonly isValid = $derived(this.validationErrors.length === 0);

	/** Whether this function is verified (has 'verified' flag) */
	readonly isVerified = $derived(this.function?.flags.includes('verified') ?? false);

	/** Whether this function is unverified (does not have 'verified' flag) */
	readonly isUnverified = $derived(!this.isVerified);

	/** Whether this function has been batch-processed (has 'processed' flag). Plain getter to avoid reactive overhead. */
	get isProcessed(): boolean {
		return this.function?.flags.includes('processed') ?? false;
	}

	/** Whether this function is invalid (fails validation) */
	readonly isInvalid = $derived(!this.isValid);

	constructor(fn: ScrFunction, isNew = false) {
		this.function = fn;
		this._originalFunction = JSON.stringify(fn);
		this.isNew = isNew;
	}

	private markDirty() {
		this._dirty = true;
	}

	/** Mark this function for deletion */
	markDeleted() {
		this.deleted = true;
	}

	/** Restore this function from deletion */
	restore() {
		this.deleted = false;
	}

	setName(name: string) {
		this.function.name = name;
		this.markDirty();
	}

	setDescription(description: string) {
		this.function.description = description || null;
		this.markDirty();
	}

	setExample(example: string) {
		this.function.example = example || null;
		this.markDirty();
	}

	setConfidence(value: 'low' | 'medium' | 'high' | null) {
		this.function.confidence = value;
		this.markDirty();
	}

	toggleFlag(flag: string) {
		if (this.function.flags.includes(flag)) {
			this.function.flags = this.function.flags.filter((f) => f !== flag);
		} else {
			let newFlags = [...this.function.flags, flag];
			// Enforce mutual exclusivity between autogenerated, verified, and processed
			const exclusiveFlags = ['autogenerated', 'verified', 'processed'];
			if (exclusiveFlags.includes(flag)) {
				newFlags = newFlags.filter((f) => f === flag || !exclusiveFlags.includes(f));
			}
			this.function.flags = newFlags;
		}
		this.markDirty();
	}

	// --- Returns editing methods ---

	private ensureReturns(overloadIndex: number): ScrReturnValue {
		const overload = this.function.overloads[overloadIndex];
		overload.returns ??= { void: true };
		return overload.returns;
	}

	setReturnsVoid(overloadIndex: number, isVoid: boolean) {
		const returns = this.ensureReturns(overloadIndex);
		if (isVoid) {
			// Clear type info when setting to void
			returns.void = true;
			returns.type = null;
			returns.name = null;
			returns.description = null;
		} else {
			returns.void = false;
		}
		// Trigger reactivity by reassigning the overloads array
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setReturnsType(overloadIndex: number, type: ScrDataType | null) {
		const returns = this.ensureReturns(overloadIndex);
		returns.type = type;
		returns.void = false;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setReturnsName(overloadIndex: number, name: string) {
		const returns = this.ensureReturns(overloadIndex);
		returns.name = name || null;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setReturnsDescription(overloadIndex: number, description: string) {
		const returns = this.ensureReturns(overloadIndex);
		returns.description = description || null;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	// --- CalledOn editing methods ---

	private ensureCalledOn(overloadIndex: number): ScrFunctionParameter {
		const overload = this.function.overloads[overloadIndex];
		overload.calledOn ??= { type: null };
		return overload.calledOn;
	}

	setCalledOnEnabled(overloadIndex: number, enabled: boolean) {
		const overload = this.function.overloads[overloadIndex];
		if (enabled) {
			overload.calledOn ??= { type: null };
		} else {
			overload.calledOn = null;
		}
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setCalledOnType(overloadIndex: number, type: ScrDataType | null) {
		const calledOn = this.ensureCalledOn(overloadIndex);
		calledOn.type = type;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setCalledOnName(overloadIndex: number, name: string) {
		const calledOn = this.ensureCalledOn(overloadIndex);
		calledOn.name = name || null;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setCalledOnDescription(overloadIndex: number, description: string) {
		const calledOn = this.ensureCalledOn(overloadIndex);
		calledOn.description = description || null;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	// --- Parameters editing methods ---

	addParameter(overloadIndex: number) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters = [
			...overload.parameters,
			{ name: 'new_param', description: null, mandatory: true, type: null }
		];
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	removeParameter(overloadIndex: number, paramIndex: number) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters = overload.parameters.filter((_, i) => i !== paramIndex);
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setParameterName(overloadIndex: number, paramIndex: number, name: string) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters[paramIndex].name = name || null;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setParameterDescription(overloadIndex: number, paramIndex: number, description: string) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters[paramIndex].description = description || null;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setParameterType(overloadIndex: number, paramIndex: number, type: ScrDataType | null) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters[paramIndex].type = type;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setParameterMandatory(overloadIndex: number, paramIndex: number, mandatory: boolean) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters[paramIndex].mandatory = mandatory;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	setParameterVariadic(overloadIndex: number, paramIndex: number, variadic: boolean) {
		const overload = this.function.overloads[overloadIndex];
		overload.parameters[paramIndex].variadic = variadic;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	moveParameter(overloadIndex: number, paramIndex: number, direction: 'up' | 'down') {
		const overload = this.function.overloads[overloadIndex];
		const newIndex = direction === 'up' ? paramIndex - 1 : paramIndex + 1;

		if (newIndex < 0 || newIndex >= overload.parameters.length) return;

		const params = [...overload.parameters];
		[params[paramIndex], params[newIndex]] = [params[newIndex], params[paramIndex]];
		overload.parameters = params;
		this.function.overloads = [...this.function.overloads];
		this.markDirty();
	}

	// --- Remarks editing methods ---

	addRemark() {
		this.function.remarks = [...(this.function.remarks ?? []), ''];
		this.markDirty();
	}

	removeRemark(index: number) {
		if (!this.function.remarks) return;
		this.function.remarks = this.function.remarks.filter((_, i) => i !== index);
		if (this.function.remarks.length === 0) {
			this.function.remarks = null;
		}
		this.markDirty();
	}

	setRemark(index: number, value: string) {
		if (!this.function.remarks) return;
		this.function.remarks[index] = value;
		this.function.remarks = [...this.function.remarks];
		this.markDirty();
	}

	moveRemark(index: number, direction: 'up' | 'down') {
		if (!this.function.remarks) return;
		const newIndex = direction === 'up' ? index - 1 : index + 1;
		if (newIndex < 0 || newIndex >= this.function.remarks.length) return;

		const remarks = [...this.function.remarks];
		[remarks[index], remarks[newIndex]] = [remarks[newIndex], remarks[index]];
		this.function.remarks = remarks;
	}

	// --- Overload editing methods ---

	addOverload() {
		const newOverload: ScrFunctionOverload = {
			calledOn: null,
			parameters: [],
			returns: { void: true }
		};
		this.function.overloads = [...this.function.overloads, newOverload];
	}

	removeOverload(overloadIndex: number) {
		if (this.function.overloads.length <= 1) return;
		this.function.overloads = this.function.overloads.filter((_, i) => i !== overloadIndex);
	}

	duplicateOverload(overloadIndex: number) {
		const source = this.function.overloads[overloadIndex];
		const duplicate: ScrFunctionOverload = JSON.parse(JSON.stringify(source));
		const newOverloads = [...this.function.overloads];
		newOverloads.splice(overloadIndex + 1, 0, duplicate);
		this.function.overloads = newOverloads;
	}
}
