#!/usr/bin/env python3
"""
API Editor CLI Tool

Manages the processing of unverified API entries in GSCode's API JSON files.
Works on copies in .tmp/ — never modifies the originals.

Usage:
    python api_editor.py stats
    python api_editor.py next [--file gsc|csc] [--skip-autogenerated]
    python api_editor.py get <name> [--file gsc|csc]
    python api_editor.py similar <name> [--file gsc|csc] [--limit N]
    python api_editor.py context <name> [--file gsc|csc]
    python api_editor.py save <name> <confidence> [--file gsc|csc]  (reads JSON from stdin)
    python api_editor.py lint <name> [--file gsc|csc]
    python api_editor.py batch-validate [--file gsc|csc]
"""

import argparse
import json
import re
import sys
from pathlib import Path
from difflib import SequenceMatcher
from collections import Counter

SCRIPT_DIR = Path(__file__).parent.resolve()

FILES = {
    "gsc": SCRIPT_DIR / "t7_api_gsc_working.json",
    "csc": SCRIPT_DIR / "t7_api_csc_working.json",
}

# Original read-only files for reference
ORIGINALS = {
    "gsc": SCRIPT_DIR.parent / "server" / "GSCode.NET" / "api" / "t7_api_gsc.json",
    "csc": SCRIPT_DIR.parent / "server" / "GSCode.NET" / "api" / "t7_api_csc.json",
}

VALID_CONFIDENCES = {"low", "medium", "high"}
PROCESSED_FLAG = "processed"
UNVERIFIED_FLAGS = {"autogenerated", "autoprocessed"}

# Common British -> American English substitutions
BRITISH_TO_AMERICAN = {
    "colour": "color",
    "colours": "colors",
    "coloured": "colored",
    "colouring": "coloring",
    "favour": "favor",
    "favours": "favors",
    "favourite": "favorite",
    "honour": "honor",
    "honours": "honors",
    "honoured": "honored",
    "behaviour": "behavior",
    "behaviours": "behaviors",
    "neighbour": "neighbor",
    "neighbours": "neighbors",
    "centre": "center",
    "centres": "centers",
    "metre": "meter",
    "metres": "meters",
    "litre": "liter",
    "litres": "liters",
    "defence": "defense",
    "offence": "offense",
    "licence": "license",
    "practise": "practice",
    "analyse": "analyze",
    "analyses": "analyzes",
    "analysed": "analyzed",
    "analysing": "analyzing",
    "catalogue": "catalog",
    "dialogue": "dialog",
    "programme": "program",
    "specialise": "specialize",
    "specialised": "specialized",
    "specialises": "specializes",
    "organise": "organize",
    "organised": "organized",
    "organises": "organizes",
    "recognise": "recognize",
    "recognised": "recognized",
    "recognises": "recognizes",
    "initialise": "initialize",
    "initialised": "initialized",
    "initialises": "initializes",
    "normalise": "normalize",
    "normalised": "normalized",
    "normalises": "normalizes",
    "serialise": "serialize",
    "serialised": "serialized",
    "serialises": "serializes",
    "synchronise": "synchronize",
    "synchronised": "synchronized",
    "synchronises": "synchronizes",
    "utilise": "utilize",
    "utilised": "utilized",
    "utilises": "utilizes",
    "optimise": "optimize",
    "optimised": "optimized",
    "optimises": "optimizes",
    "cancelled": "canceled",
    "cancelling": "canceling",
    "modelling": "modeling",
    "modelled": "modeled",
    "travelling": "traveling",
    "travelled": "traveled",
    "labelling": "labeling",
    "labelled": "labeled",
    "grey": "gray",
    "armour": "armor",
    "armoured": "armored",
    "mould": "mold",
    "manoeuvre": "maneuver",
}


# ─── File I/O ────────────────────────────────────────────────────────────────

def load_api(file_key: str) -> list[dict]:
    path = FILES[file_key]
    if not path.exists():
        print(f"Error: Working file not found: {path}", file=sys.stderr)
        print("Copy the originals first:", file=sys.stderr)
        print(f"  cp server/GSCode.NET/api/t7_api_gsc.json .tmp/t7_api_gsc_working.json", file=sys.stderr)
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return json.load(f)["api"]


def save_api(file_key: str, entries: list[dict]):
    path = FILES[file_key]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump({"api": entries}, f, indent=4, ensure_ascii=False)
        f.write("\n")


def load_original(file_key: str) -> list[dict]:
    path = ORIGINALS[file_key]
    if not path.exists():
        return []
    with open(path, encoding="utf-8") as f:
        return json.load(f)["api"]


def find_entry(entries: list[dict], name: str) -> tuple[int, dict] | None:
    name_lower = name.lower()
    for i, entry in enumerate(entries):
        if entry["name"].lower() == name_lower:
            return i, entry
    return None


def get_flags(entry: dict) -> set[str]:
    return set(entry.get("flags", []))


def get_state(entry: dict) -> str:
    flags = get_flags(entry)
    if "verified" in flags:
        return "verified"
    if PROCESSED_FLAG in flags:
        return "processed"
    if "autoprocessed" in flags:
        return "autoprocessed"
    if "autogenerated" in flags:
        return "autogenerated"
    return "unknown"


# ─── Linting ─────────────────────────────────────────────────────────────────

def is_pascal_case(name: str) -> bool:
    """Check if name is PascalCase. Underscores are allowed as segment separators,
    but each segment must start with an uppercase letter (e.g. Bb_GetArrivalStance)."""
    if not name:
        return False
    if " " in name:
        return False
    segments = name.split("_") if "_" in name else [name]
    for seg in segments:
        if not seg or not seg[0].isupper():
            return False
    return True


def is_camel_case(name: str) -> bool:
    """Check if name is camelCase (first char lowercase, no spaces)."""
    if not name:
        return False
    if " " in name:
        return False
    if not name[0].islower():
        return False
    return True


def is_generic_param_name(name: str) -> bool:
    """Check if param name is a generic placeholder like arg0, arg1, etc."""
    return bool(re.match(r"^arg\d+$", name))


def find_british_spellings(text: str) -> list[tuple[str, str]]:
    """Find British English spellings in text, return (british, american) pairs."""
    if not text:
        return []
    findings = []
    words = re.findall(r"[a-zA-Z]+", text.lower())
    for word in words:
        if word in BRITISH_TO_AMERICAN:
            findings.append((word, BRITISH_TO_AMERICAN[word]))
    return findings


def lint_entry(entry: dict) -> list[str]:
    """Lint a single API entry, return list of issues."""
    issues = []
    name = entry.get("name", "")
    state = get_state(entry)

    # Function name: PascalCase
    if not is_pascal_case(name):
        issues.append(f"Function name '{name}' is not PascalCase")

    # Description: non-empty, ends with period
    desc = entry.get("description", "")
    if not desc or not desc.strip():
        issues.append("Missing function description")
    elif not desc.strip().endswith("."):
        issues.append(f"Description does not end with a period: \"{desc}\"")

    # British spellings in description
    british = find_british_spellings(desc)
    for brit, amer in british:
        issues.append(f"British spelling '{brit}' in description — use '{amer}'")

    # Confidence field (required for processed)
    if state == "processed":
        conf = entry.get("confidence")
        if conf not in VALID_CONFIDENCES:
            issues.append(f"Processed entry missing valid confidence (got '{conf}')")

    # Overloads
    for ov_idx, overload in enumerate(entry.get("overloads", [])):
        ov_prefix = f"Overload {ov_idx + 1}: " if len(entry.get("overloads", [])) > 1 else ""

        # CalledOn
        called_on = overload.get("calledOn")
        if called_on and isinstance(called_on, dict):
            co_name = called_on.get("name", "")
            co_desc = called_on.get("description")
            if co_name and not is_camel_case(co_name):
                issues.append(f"{ov_prefix}CalledOn name '{co_name}' is not camelCase")
            if not co_desc:
                issues.append(f"{ov_prefix}CalledOn '{co_name}' missing description")
            elif not co_desc.strip().endswith("."):
                issues.append(f"{ov_prefix}CalledOn description does not end with period")
            british = find_british_spellings(co_desc or "")
            for brit, amer in british:
                issues.append(f"{ov_prefix}CalledOn: British spelling '{brit}' — use '{amer}'")

        # Parameters
        for p_idx, param in enumerate(overload.get("parameters", [])):
            p_name = param.get("name", "")
            p_desc = param.get("description", "")
            p_prefix = f"{ov_prefix}Param '{p_name}'"

            # Name checks
            if is_generic_param_name(p_name):
                issues.append(f"{p_prefix}: generic placeholder name")
            elif not is_camel_case(p_name):
                issues.append(f"{p_prefix}: not camelCase")

            # Description checks
            if not p_desc or not p_desc.strip():
                issues.append(f"{p_prefix}: missing description")
            elif not p_desc.strip().endswith("."):
                issues.append(f"{p_prefix}: description does not end with period")

            # British spellings
            british = find_british_spellings(p_desc)
            for brit, amer in british:
                issues.append(f"{p_prefix}: British spelling '{brit}' — use '{amer}'")

        # Returns
        returns = overload.get("returns")
        if returns and not returns.get("void", False):
            ret_type = returns.get("type")
            if not ret_type:
                issues.append(f"{ov_prefix}Non-void return but missing return type")

    # Example
    example = entry.get("example", "")
    if not example or not example.strip():
        issues.append("Missing example")

    return issues


# ─── Commands ────────────────────────────────────────────────────────────────

def cmd_stats(args):
    """Show counts by state and progress."""
    print("=" * 60)
    print("API Processing Progress")
    print("=" * 60)

    grand_total = 0

    for fk in ["gsc", "csc"]:
        entries = load_api(fk)
        counts = Counter()
        for entry in entries:
            counts[get_state(entry)] += 1

        total = len(entries)
        grand_total += total

        processable = counts["autogenerated"] + counts["autoprocessed"]
        processed = counts["processed"]
        done_pct = (processed / (processable + processed) * 100) if (processable + processed) > 0 else 0

        # Confidence breakdown
        conf_counts = Counter()
        for entry in entries:
            if get_state(entry) == "processed":
                conf_counts[entry.get("confidence", "none")] += 1

        print(f"\n  {fk.upper()} ({total} total)")
        print(f"  {'-' * 40}")
        print(f"    Verified:       {counts['verified']:>5}")
        print(f"    Autogenerated:  {counts['autogenerated']:>5}")
        print(f"    Autoprocessed:  {counts['autoprocessed']:>5}")
        print(f"    Processed:      {counts['processed']:>5}")
        if counts.get("unknown", 0):
            print(f"    Other:          {counts['unknown']:>5}")
        print(f"  {'-' * 40}")
        print(f"    Progress: {processed}/{processable + processed} ({done_pct:.1f}%)")

        if processed > 0:
            print(f"    Confidence: high={conf_counts.get('high', 0)}"
                  f"  medium={conf_counts.get('medium', 0)}"
                  f"  low={conf_counts.get('low', 0)}")

    # Grand totals
    grand_counts = Counter()
    for fk in ["gsc", "csc"]:
        entries = load_api(fk)
        for entry in entries:
            grand_counts[get_state(entry)] += 1

    processable = grand_counts["autogenerated"] + grand_counts["autoprocessed"]
    processed = grand_counts["processed"]
    done_pct = (processed / (processable + processed) * 100) if (processable + processed) > 0 else 0

    print(f"\n  TOTAL ({grand_total} entries)")
    print(f"  {'-' * 40}")
    print(f"    Remaining:      {processable:>5}")
    print(f"    Processed:      {processed:>5}")
    print(f"    Progress: {processed}/{processable + processed} ({done_pct:.1f}%)")
    print()


def cmd_next(args):
    """Get next unprocessed entry."""
    file_keys = [args.file] if args.file else ["gsc", "csc"]

    for fk in file_keys:
        entries = load_api(fk)
        for entry in entries:
            state = get_state(entry)
            if state == "autoprocessed" or (state == "autogenerated" and not args.skip_autogenerated):
                # Prefer autoprocessed first (they need more work)
                print(json.dumps(entry, indent=4, ensure_ascii=False))
                print(f"\n# File: {fk} | State: {state} | Name: {entry['name']}", file=sys.stderr)
                return

    print("No unprocessed entries found!", file=sys.stderr)


def cmd_get(args):
    """Get a specific entry."""
    file_keys = [args.file] if args.file else ["gsc", "csc"]

    for fk in file_keys:
        entries = load_api(fk)
        result = find_entry(entries, args.name)
        if result:
            _, entry = result
            print(json.dumps(entry, indent=4, ensure_ascii=False))
            print(f"\n# File: {fk} | State: {get_state(entry)}", file=sys.stderr)
            return

    print(f"Entry '{args.name}' not found", file=sys.stderr)
    sys.exit(1)


def _name_similarity(a: str, b: str) -> float:
    """Compute similarity between two function names."""
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


def _extract_keywords(name: str) -> set[str]:
    """Split PascalCase name into keyword tokens."""
    # Split on uppercase boundaries
    tokens = re.findall(r"[A-Z][a-z0-9]*|[a-z][a-z0-9]*", name)
    return {t.lower() for t in tokens}


def cmd_similar(args):
    """Find verified entries similar to a given name."""
    file_keys = [args.file] if args.file else ["gsc", "csc"]
    limit = args.limit or 5
    target_name = args.name
    target_keywords = _extract_keywords(target_name)

    # Collect all verified entries across files
    candidates = []
    for fk in ["gsc", "csc"]:
        entries = load_api(fk)
        for entry in entries:
            if get_state(entry) == "verified":
                entry_keywords = _extract_keywords(entry["name"])
                # Score: keyword overlap + name similarity
                overlap = len(target_keywords & entry_keywords)
                sim = _name_similarity(target_name, entry["name"])
                score = overlap * 2 + sim
                candidates.append((score, fk, entry))

    candidates.sort(key=lambda x: -x[0])

    if not candidates:
        print("No verified entries found for reference", file=sys.stderr)
        return

    print(f"# Top {limit} verified entries similar to '{target_name}':\n")
    for score, fk, entry in candidates[:limit]:
        print(f"# --- {entry['name']} ({fk}) [score: {score:.2f}] ---")
        print(json.dumps(entry, indent=4, ensure_ascii=False))
        print()


def cmd_context(args):
    """Show an entry alongside similar verified entries for reference."""
    file_keys = [args.file] if args.file else ["gsc", "csc"]

    # Find the target entry
    target = None
    target_fk = None
    for fk in file_keys:
        entries = load_api(fk)
        result = find_entry(entries, args.name)
        if result:
            _, target = result
            target_fk = fk
            break

    if not target:
        print(f"Entry '{args.name}' not found", file=sys.stderr)
        sys.exit(1)

    state = get_state(target)
    issues = lint_entry(target)

    print(f"# ==========================================================")
    print(f"# TARGET: {target['name']} ({target_fk.upper()})")
    print(f"# State: {state}")
    if target.get("confidence"):
        print(f"# Confidence: {target['confidence']}")
    print(f"# Lint issues: {len(issues)}")
    for issue in issues:
        print(f"#   - {issue}")
    print(f"# ==========================================================")
    print()
    print(json.dumps(target, indent=4, ensure_ascii=False))

    # Show similar verified entries
    target_keywords = _extract_keywords(target["name"])
    candidates = []
    for fk in ["gsc", "csc"]:
        entries = load_api(fk)
        for entry in entries:
            if get_state(entry) == "verified":
                entry_keywords = _extract_keywords(entry["name"])
                overlap = len(target_keywords & entry_keywords)
                sim = _name_similarity(target["name"], entry["name"])
                score = overlap * 2 + sim
                candidates.append((score, fk, entry))

    candidates.sort(key=lambda x: -x[0])

    if candidates:
        print(f"\n\n# -- Reference: Similar verified entries ------------------")
        for score, fk, entry in candidates[:3]:
            print(f"\n# --- {entry['name']} ({fk}) ---")
            print(json.dumps(entry, indent=4, ensure_ascii=False))


def cmd_save(args):
    """Save an edited entry with processed flag and confidence."""
    confidence = args.confidence.lower()
    if confidence not in VALID_CONFIDENCES:
        print(f"Error: confidence must be one of: {', '.join(sorted(VALID_CONFIDENCES))}", file=sys.stderr)
        sys.exit(1)

    # Read edited JSON from stdin
    try:
        edited = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON on stdin: {e}", file=sys.stderr)
        sys.exit(1)

    file_keys = [args.file] if args.file else ["gsc", "csc"]

    for fk in file_keys:
        entries = load_api(fk)
        result = find_entry(entries, args.name)
        if result:
            idx, _old = result

            # Set the processed flag, removing autogenerated/autoprocessed
            new_flags = [f for f in edited.get("flags", []) if f not in UNVERIFIED_FLAGS]
            if PROCESSED_FLAG not in new_flags:
                new_flags.append(PROCESSED_FLAG)
            # Preserve other flags like deprecated, broken, etc.
            old_other_flags = [f for f in _old.get("flags", []) if f not in UNVERIFIED_FLAGS and f != PROCESSED_FLAG]
            for f in old_other_flags:
                if f not in new_flags:
                    new_flags.append(f)
            edited["flags"] = new_flags

            # Set confidence
            edited["confidence"] = confidence

            # Use the name from the edited JSON (allows renaming/recasing)
            # Fall back to the lookup name if not present
            if "name" not in edited:
                edited["name"] = args.name

            # Lint the result
            issues = lint_entry(edited)

            # Save
            entries[idx] = edited
            save_api(fk, entries)

            print(f"Saved '{args.name}' to {fk} with confidence={confidence}", file=sys.stderr)
            if issues:
                print(f"\nLint warnings ({len(issues)}):", file=sys.stderr)
                for issue in issues:
                    print(f"  - {issue}", file=sys.stderr)
            else:
                print("Lint: all checks passed", file=sys.stderr)
            return

    print(f"Entry '{args.name}' not found in working files", file=sys.stderr)
    sys.exit(1)


def cmd_lint(args):
    """Lint a specific entry."""
    file_keys = [args.file] if args.file else ["gsc", "csc"]

    for fk in file_keys:
        entries = load_api(fk)
        result = find_entry(entries, args.name)
        if result:
            _, entry = result
            issues = lint_entry(entry)
            state = get_state(entry)

            print(f"{entry['name']} ({fk.upper()}, {state})")
            if not issues:
                print("  All checks passed.")
            else:
                for issue in issues:
                    print(f"  - {issue}")
            return

    print(f"Entry '{args.name}' not found", file=sys.stderr)
    sys.exit(1)


def cmd_batch_validate(args):
    """Validate all processed entries."""
    file_keys = [args.file] if args.file else ["gsc", "csc"]
    total_issues = 0
    total_entries = 0
    clean_entries = 0

    for fk in file_keys:
        entries = load_api(fk)
        for entry in entries:
            state = get_state(entry)
            if state != "processed":
                continue

            total_entries += 1
            issues = lint_entry(entry)

            if issues:
                total_issues += len(issues)
                print(f"\n{entry['name']} ({fk.upper()}, confidence={entry.get('confidence', '?')}):")
                for issue in issues:
                    print(f"  - {issue}")
            else:
                clean_entries += 1

    if total_entries == 0:
        print("No processed entries to validate.")
    else:
        print(f"\n{'-' * 40}")
        print(f"Validated {total_entries} processed entries")
        print(f"  Clean: {clean_entries}")
        print(f"  With issues: {total_entries - clean_entries}")
        print(f"  Total issues: {total_issues}")


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="API Editor CLI — process unverified API entries",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # stats
    subparsers.add_parser("stats", help="Show processing progress")

    # next
    p_next = subparsers.add_parser("next", help="Get next unprocessed entry")
    p_next.add_argument("--file", choices=["gsc", "csc"], default=None)
    p_next.add_argument("--skip-autogenerated", action="store_true",
                        help="Only show autoprocessed (most work needed)")

    # get
    p_get = subparsers.add_parser("get", help="Get a specific entry")
    p_get.add_argument("name", help="Function name")
    p_get.add_argument("--file", choices=["gsc", "csc"], default=None)

    # similar
    p_sim = subparsers.add_parser("similar", help="Find similar verified entries")
    p_sim.add_argument("name", help="Function name to match against")
    p_sim.add_argument("--file", choices=["gsc", "csc"], default=None)
    p_sim.add_argument("--limit", type=int, default=5)

    # context
    p_ctx = subparsers.add_parser("context", help="Show entry with reference context")
    p_ctx.add_argument("name", help="Function name")
    p_ctx.add_argument("--file", choices=["gsc", "csc"], default=None)

    # save
    p_save = subparsers.add_parser("save", help="Save edited entry (reads JSON from stdin)")
    p_save.add_argument("name", help="Function name")
    p_save.add_argument("confidence", choices=sorted(VALID_CONFIDENCES))
    p_save.add_argument("--file", choices=["gsc", "csc"], default=None)

    # lint
    p_lint = subparsers.add_parser("lint", help="Lint a specific entry")
    p_lint.add_argument("name", help="Function name")
    p_lint.add_argument("--file", choices=["gsc", "csc"], default=None)

    # batch-validate
    p_bv = subparsers.add_parser("batch-validate", help="Validate all processed entries")
    p_bv.add_argument("--file", choices=["gsc", "csc"], default=None)

    args = parser.parse_args()

    commands = {
        "stats": cmd_stats,
        "next": cmd_next,
        "get": cmd_get,
        "similar": cmd_similar,
        "context": cmd_context,
        "save": cmd_save,
        "lint": cmd_lint,
        "batch-validate": cmd_batch_validate,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
