#!/usr/bin/env python3
"""
Registry-Driven API Enrichment Script

Enriches t7_api_gsc.json and t7_api_csc.json using IDA-extracted function
signatures from gsc_function_registry.json.

Tier 1: Safe auto-apply (autogenerated entries only)
Tier 2: Review report (all entries, including verified)
Tier 3: New entry candidates
"""

import json
import re
import os
import copy
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent

REGISTRY_PATH = SCRIPT_DIR / "gsc_function_registry.json"
GSC_API_PATH = PROJECT_ROOT / "server" / "GSCode.NET" / "api" / "t7_api_gsc.json"
CSC_API_PATH = PROJECT_ROOT / "server" / "GSCode.NET" / "api" / "t7_api_csc.json"

OUTPUT_GSC = SCRIPT_DIR / "t7_api_gsc.enriched.json"
OUTPUT_CSC = SCRIPT_DIR / "t7_api_csc.enriched.json"
OUTPUT_REVIEW = SCRIPT_DIR / "registry_review_report.json"
OUTPUT_CHANGELOG = SCRIPT_DIR / "registry_changelog.json"

# ── Type Mapping ──────────────────────────────────────────────────────────────

TYPE_MAP = {
    "string":    {"dataType": "string"},
    "int":       {"dataType": "int"},
    "float":     {"dataType": "float"},
    "number":    {"dataType": "number"},
    "bool":      {"dataType": "bool"},
    "vector":    {"dataType": "vector"},
    "entity":    {"dataType": "entity"},
    "weapon":    {"dataType": "entity", "instanceType": "weapon", "subType": "weapon"},
    "array":     {"dataType": "any", "isArray": True},
    "struct":    {"dataType": "struct"},
    "istring":   {"dataType": "istring"},
    "team":      {"dataType": "string"},
    "hash":      {"dataType": "hash"},
    "function":  {"dataType": "function"},
    "anim":      {"dataType": "string"},
    "animtree":  {"dataType": "string"},
    "uint64":    {"dataType": "int"},
}

# Types too vague to backfill
SKIP_TYPES = {"any", "object", "undefined"}

# Subsumption: types that are supersets of other types (for conflict detection)
TYPE_SUBSUMES = {
    "number": {"int", "float", "number"},
    "int":    {"int"},
    "float":  {"float"},
    "string": {"string", "istring"},
}

# Safe type upgrades: (api_type, registry_type) pairs where the registry is
# strictly more accurate. The API had a narrower type from autogeneration;
# the registry's static analysis found it actually accepts more.
SAFE_UPGRADES = {
    ("float", "number"),   # Scr_GetFloat accepts int too → number
    ("int", "number"),     # Same numeric widening
    ("int", "bool"),       # Scr_GetInt used as != 0 → bool
}


def _registry_type_upgrades(api_dt: str, reg_dt: str) -> bool:
    """Return True if switching from api_dt to reg_dt is a safe upgrade."""
    # Direct single-type upgrades
    if (api_dt, reg_dt) in SAFE_UPGRADES:
        return True
    # Registry union that fully covers the API type
    # e.g. API has "int", registry has "int | string" → upgrade (more info)
    api_types = {t.strip() for t in api_dt.split("|")}
    reg_types = {t.strip() for t in reg_dt.split("|")}
    reg_expanded = set()
    for t in reg_types:
        reg_expanded |= TYPE_SUBSUMES.get(t, {t})
    if api_types <= reg_expanded and reg_types != api_types:
        return True
    return False


CALLED_ON_MAP = {
    "entity":          {"name": "entity", "description": None},
    "entity:hudelem":  {"name": "hud_element", "description": None},
    "entity:pathnode":  {"name": "pathnode", "description": None},
    "entity:vehiclenode": {"name": "vehiclenode", "description": None},
    "entity:dynentity": {"name": "dynentity", "description": None},
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def map_registry_type(reg_type: str) -> dict | None:
    """Convert a registry type string (possibly pipe-separated union) to an API type object.
    Returns None if unmappable."""
    # Split union types (e.g. "hash | int | string")
    parts = [t.strip() for t in reg_type.split("|")]
    # Filter out types too vague to backfill
    useful = [t for t in parts if t not in SKIP_TYPES]
    if not useful:
        return None

    if len(useful) == 1:
        # Single type — use TYPE_MAP directly (preserves instanceType, isArray, etc.)
        base = TYPE_MAP.get(useful[0])
        if base is None:
            return None
        result = dict(base)
        result.setdefault("isArray", False)
        return result

    # Union type: map each part through TYPE_MAP, collect dataType strings
    mapped_data_types = []
    has_array = False
    for part in useful:
        base = TYPE_MAP.get(part)
        if base is None:
            continue  # skip unknown types in union
        if base.get("isArray"):
            has_array = True
            continue  # array handled separately
        mapped_data_types.append(base["dataType"])

    # Deduplicate while preserving order
    seen = set()
    unique = []
    for dt in mapped_data_types:
        if dt not in seen:
            seen.add(dt)
            unique.append(dt)

    if has_array and not unique:
        return {"dataType": "any", "isArray": True}

    if not unique:
        return None

    # Join as pipe-separated union (the LSP parser handles this)
    data_type = " | ".join(unique)
    result = {"dataType": data_type, "isArray": has_array}
    return result


def map_return_type(reg_entry: dict) -> dict | None:
    """Build an API returns object from registry return info. Returns None if not useful."""
    rt = reg_entry.get("return_type", "void")
    if rt == "void":
        return None

    # Parse union types
    types = [t.strip() for t in rt.split("|")]
    # Filter out undefined/void/skip types
    useful = [t for t in types if t not in ("void", "undefined") and t not in SKIP_TYPES]
    if not useful:
        return None

    # Rejoin the useful parts and map through the union-aware map_registry_type
    rejoined = " | ".join(useful)
    mapped = map_registry_type(rejoined)
    if mapped is None:
        return None

    # Add entity subtypes if available
    subtypes = reg_entry.get("return_subtypes", [])
    data_type_str = mapped.get("dataType", "")
    if ("entity" in data_type_str) and subtypes:
        for st in subtypes:
            if ":" in st:
                subname = st.split(":", 1)[1]
                mapped["instanceType"] = subname
                mapped["subType"] = subname
                break

    return {
        "name": None,
        "description": None,
        "type": mapped,
        "void": False
    }


def is_autogenerated_only(entry: dict) -> bool:
    """Check if entry is autogenerated (not verified or unlisted)."""
    flags = entry.get("flags", [])
    return "autogenerated" in flags and "verified" not in flags and "unlisted" not in flags


def has_return(overload: dict) -> bool:
    """Check if an overload already has a meaningful return type."""
    ret = overload.get("returns")
    if ret is None:
        return False
    if ret.get("void", False):
        return False
    if ret.get("type") is None:
        return False
    return True


def extract_handler_name(handler: str) -> str | None:
    """Extract the clean function name from a mangled handler string."""
    if handler is None:
        return None

    # Mangled C++ name: _ZL<digits><Name><rest>
    m = re.match(r'_ZL\d+(\w+?)(?:16scriptInstance_t|10scr_entref)', handler)
    if m:
        return m.group(1)

    # Direct name like GScr_SpawnFX, PlayerCmd_Foo
    return handler


def get_handler_prefix(handler: str) -> str | None:
    """Extract the prefix category from a handler name."""
    if handler is None:
        return None

    name = extract_handler_name(handler)
    if name is None:
        return None

    # Check known prefixes (longer first to avoid partial matches)
    for prefix in ["OldBotCmd_", "BotCmd_", "BGScr_", "CScrCmd_", "CScr_", "GScr_", "CMD_", "ScrCmd_", "PlayerCmd_", "ActorCmd_", "Scr_"]:
        if name.startswith(prefix):
            return prefix.rstrip("_")

    return "other"


def recover_cased_name(reg_entry: dict) -> str:
    """Try to recover the properly-cased function name from handler or error strings."""
    handler = reg_entry.get("handler")
    name_lower = reg_entry["name"]

    # Try handler name: strip known prefixes (including OldBotCmd_Bot, BotCmd_, etc.)
    if handler:
        clean = extract_handler_name(handler)
        if clean:
            # Extended prefix list — order matters (longer/more specific first)
            handler_prefixes = [
                "OldBotCmd_Bot", "OldBotCmd_",
                "BotCmd_",
                "BGScr_", "CScr_", "CScrCmd_",
                "GScr_", "CMD_", "ScrCmd_",
                "PlayerCmd_", "ActorCmd_",
                "Scr_",
            ]
            for prefix in handler_prefixes:
                if clean.startswith(prefix):
                    candidate = clean[len(prefix):]
                    if candidate.lower() == name_lower:
                        return candidate
                    # Also try with "Bot" prefix stripped from the function name
                    # e.g. handler BotCmd_CancelPath → name botcancelpath
                    # so candidate is CancelPath, and "Bot" + candidate = BotCancelPath
                    if prefix.startswith("BotCmd") or prefix.startswith("OldBotCmd"):
                        bot_candidate = "Bot" + candidate
                        if bot_candidate.lower() == name_lower:
                            return bot_candidate

    # Try error strings
    for err in reg_entry.get("error_strings", []):
        # Look for the function name at the start of error messages
        # e.g. "SpawnFx called with..." → SpawnFx
        words = re.split(r'[\s:()\[\],]', err)
        for word in words:
            if word.lower() == name_lower and word != name_lower:
                return word

    # Fallback: capitalize first letter only
    return name_lower[0].upper() + name_lower[1:] if name_lower else name_lower


def classify_for_api(reg_entry: dict, gsc_names: set, csc_names: set) -> list[str]:
    """Determine which API file(s) a new entry should be added to.
    Returns list of 'gsc', 'csc', or both."""
    prefix = get_handler_prefix(reg_entry.get("handler"))

    if prefix in ("CScr", "CScrCmd"):
        return ["csc"]
    elif prefix in ("GScr", "CMD", "ScrCmd", "PlayerCmd", "ActorCmd", "BotCmd", "OldBotCmd"):
        return ["gsc"]
    elif prefix == "BGScr":
        return ["gsc", "csc"]
    else:
        return ["gsc"]  # default


def build_new_entry(reg_entry: dict) -> dict:
    """Build an API entry from a registry entry for Tier 3."""
    name = recover_cased_name(reg_entry)
    min_args = reg_entry.get("min_args") or 0
    max_args = reg_entry.get("max_args") or 0

    # Build parameters
    params = []
    for p in sorted(reg_entry.get("parameters", []), key=lambda x: x["index"]):
        idx = p["index"]
        mapped_type = map_registry_type(p["type"])
        param = {
            "name": f"arg{idx}",
            "description": "",
            "mandatory": idx < min_args,
        }
        if mapped_type:
            param["type"] = mapped_type
        params.append(param)

    # Fill gaps: if max_args > len(params), there are params we couldn't detect
    existing_indices = {p["index"] for p in reg_entry.get("parameters", [])}
    for i in range(max_args):
        if i not in existing_indices:
            params.append({
                "name": f"arg{i}",
                "description": "",
                "mandatory": i < min_args,
            })
    params.sort(key=lambda p: int(p["name"].replace("arg", "")) if p["name"].startswith("arg") else 999)

    # Build calledOn
    called_on = None
    if reg_entry["kind"] == "method":
        co = reg_entry.get("called_on")
        if co and co in CALLED_ON_MAP:
            called_on = dict(CALLED_ON_MAP[co])
        else:
            called_on = {"name": "entity", "description": None}

    # Build overload
    overload = {
        "calledOn": called_on,
        "parameters": params,
    }

    # Add returns if non-void
    ret = map_return_type(reg_entry)
    if ret:
        overload["returns"] = ret

    entry = {
        "name": name,
        "description": "",
        "overloads": [overload],
        "flags": ["autoprocessed"],
        "example": ""
    }

    return entry


# ── Main Logic ────────────────────────────────────────────────────────────────

def main():
    # Load data
    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        registry = json.load(f)

    with open(GSC_API_PATH, "r", encoding="utf-8") as f:
        gsc_data = json.load(f)

    with open(CSC_API_PATH, "r", encoding="utf-8") as f:
        csc_data = json.load(f)

    # Deep copy for output
    gsc_out = copy.deepcopy(gsc_data)
    csc_out = copy.deepcopy(csc_data)

    # Build lookup maps
    reg_map = {}
    for e in registry:
        reg_map[e["name"].lower()] = e

    gsc_map = {}
    for i, e in enumerate(gsc_out["api"]):
        gsc_map[e["name"].lower()] = (e, i)

    csc_map = {}
    for i, e in enumerate(csc_out["api"]):
        csc_map[e["name"].lower()] = (e, i)

    gsc_names = set(gsc_map.keys())
    csc_names = set(csc_map.keys())

    changelog = []
    review_report = []
    stats = {
        "tier1_param_types_added": 0,
        "tier1_return_types_added": 0,
        "tier1_mandatory_fixed": 0,
        "tier1_calledon_added": 0,
        "tier2_issues_flagged": 0,
        "tier3_gsc_added": 0,
        "tier3_csc_added": 0,
    }

    # Track which names exist in both APIs (for cross-file mismatch suppression)
    shared_api_names = gsc_names & csc_names

    def is_vararg(reg_entry: dict) -> bool:
        """Detect vararg functions: max_args < min_args (e.g. min=1, max=0)."""
        mn = reg_entry.get("min_args")
        mx = reg_entry.get("max_args")
        if mn is not None and mx is not None and mx < mn:
            return True
        return False

    # ── TIER 1: Safe Auto-Apply ───────────────────────────────────────────

    def apply_tier1(api_map: dict, file_label: str):
        for name_lower, reg in reg_map.items():
            if name_lower not in api_map:
                continue

            api_entry, _ = api_map[name_lower]

            if not is_autogenerated_only(api_entry):
                continue

            overloads = api_entry.get("overloads", [])
            if len(overloads) != 1:
                continue  # skip multi-overload entries

            ov = overloads[0]
            api_params = ov.get("parameters", [])
            reg_params = sorted(reg.get("parameters", []), key=lambda x: x["index"])
            min_args = reg.get("min_args")
            max_args = reg.get("max_args")
            vararg = is_vararg(reg)

            changes = []

            # 1a. Backfill or upgrade param types (skip vararg — index alignment unreliable)
            if not vararg and max_args is not None and len(api_params) == max_args:
                reg_param_map = {p["index"]: p for p in reg_params}
                for i, ap in enumerate(api_params):
                    if i not in reg_param_map:
                        continue
                    reg_type = reg_param_map[i]["type"]
                    mapped = map_registry_type(reg_type)
                    if mapped is None:
                        continue

                    if "type" not in ap:
                        # No type at all — backfill
                        ap["type"] = mapped
                        changes.append({
                            "field": f"parameters[{i}].type",
                            "added": mapped
                        })
                        stats["tier1_param_types_added"] += 1
                    else:
                        # Type exists — upgrade if registry is strictly more precise
                        api_dt = ap["type"].get("dataType", "")
                        reg_dt = mapped.get("dataType", "")
                        if api_dt != reg_dt and _registry_type_upgrades(api_dt, reg_dt):
                            old_type = dict(ap["type"])
                            ap["type"] = mapped
                            changes.append({
                                "field": f"parameters[{i}].type",
                                "from": old_type,
                                "to": mapped
                            })
                            stats["tier1_param_types_added"] += 1

            # 1b. Backfill return types
            if not has_return(ov):
                ret = map_return_type(reg)
                if ret:
                    ov["returns"] = ret
                    changes.append({
                        "field": "returns",
                        "added": ret
                    })
                    stats["tier1_return_types_added"] += 1

            # 1c. Fix mandatory flags (skip vararg — all params are effectively optional/variadic)
            if (not vararg
                    and min_args is not None and max_args is not None
                    and min_args < max_args
                    and len(api_params) == max_args):
                for i, ap in enumerate(api_params):
                    if i >= min_args and ap.get("mandatory", False):
                        ap["mandatory"] = False
                        changes.append({
                            "field": f"parameters[{i}].mandatory",
                            "from": True,
                            "to": False
                        })
                        stats["tier1_mandatory_fixed"] += 1

            # 1d. Backfill calledOn
            if reg["kind"] == "method" and reg.get("called_on"):
                if ov.get("calledOn") is None:
                    mapped_co = CALLED_ON_MAP.get(reg["called_on"])
                    if mapped_co:
                        ov["calledOn"] = dict(mapped_co)
                        changes.append({
                            "field": "calledOn",
                            "added": dict(mapped_co)
                        })
                        stats["tier1_calledon_added"] += 1

            if changes:
                changelog.append({
                    "name": api_entry["name"],
                    "file": file_label,
                    "changes": changes
                })

    apply_tier1(gsc_map, "t7_api_gsc")
    apply_tier1(csc_map, "t7_api_csc")

    # ── TIER 2: Review Report ─────────────────────────────────────────────

    def build_tier2(api_map: dict, other_api_map: dict, file_label: str):
        for name_lower, reg in reg_map.items():
            if name_lower not in api_map:
                continue

            api_entry, _ = api_map[name_lower]
            flags = api_entry.get("flags", [])
            is_verified = "verified" in flags
            severity = "high" if is_verified else "medium"
            vararg = is_vararg(reg)

            # Cross-file suppression: if this name exists in both APIs,
            # the registry entry may only match one side's signature.
            # Only flag kind/param mismatches if the entry is NOT in the other API,
            # or if both APIs show the same mismatch pattern.
            in_other_api = name_lower in other_api_map

            issues = []

            for ov_idx, ov in enumerate(api_entry.get("overloads", [])):
                api_params = ov.get("parameters", [])
                min_args = reg.get("min_args")
                max_args = reg.get("max_args")

                # 2a/2c. Param count mismatch
                if vararg:
                    # Vararg: flag as informational, not as a real mismatch
                    if len(api_params) < (min_args or 0):
                        issues.append({
                            "type": "vararg_min_args_not_met",
                            "overload_index": ov_idx,
                            "api_count": len(api_params),
                            "registry_min": min_args,
                            "note": "vararg function (max < min), API has fewer params than minimum",
                            "severity": severity
                        })
                elif max_args is not None and len(api_params) != max_args:
                    # For autogenerated with single overload, this is noteworthy
                    # For verified, always flag
                    # For multi-overload autogenerated, skip (already complex)
                    if is_verified or len(api_entry.get("overloads", [])) == 1:
                        issues.append({
                            "type": "param_count_mismatch",
                            "overload_index": ov_idx,
                            "api_count": len(api_params),
                            "registry_min": min_args,
                            "registry_max": max_args,
                            "registry_overloads": reg.get("overload_param_counts", []),
                            "severity": severity
                        })

                # 2a. Verified missing return
                if is_verified and not has_return(ov):
                    rt = reg.get("return_type", "void")
                    if rt != "void":
                        useful = [t.strip() for t in rt.split("|") if t.strip() not in ("void", "undefined")]
                        if useful:
                            issues.append({
                                "type": "missing_return_type",
                                "overload_index": ov_idx,
                                "registry_return": rt,
                                "severity": severity
                            })

                # 2b. Kind mismatch — suppress for entries in both APIs
                # (the registry may describe one VM's version, not both)
                api_is_method = ov.get("calledOn") is not None
                reg_is_method = reg["kind"] == "method"
                if api_is_method != reg_is_method and not in_other_api:
                    issues.append({
                        "type": "kind_mismatch",
                        "overload_index": ov_idx,
                        "api_kind": "method" if api_is_method else "function",
                        "registry_kind": reg["kind"],
                        "registry_called_on": reg.get("called_on"),
                        "severity": severity
                    })

                # 2d. Type conflicts (skip vararg — index alignment unreliable)
                if not vararg and max_args is not None and len(api_params) == max_args:
                    reg_param_map = {p["index"]: p for p in reg.get("parameters", [])}
                    for i, ap in enumerate(api_params):
                        if "type" in ap and i in reg_param_map:
                            reg_type = reg_param_map[i]["type"]
                            mapped = map_registry_type(reg_type)
                            if mapped:
                                api_dt = ap["type"].get("dataType", "")
                                reg_dt = mapped.get("dataType", "")
                                # Parse both sides as sets of types for comparison
                                api_types = {t.strip() for t in api_dt.split("|")}
                                reg_types = {t.strip() for t in reg_dt.split("|")}
                                # Expand subsumption (e.g. "number" covers "int" and "float")
                                api_expanded = set()
                                for t in api_types:
                                    api_expanded |= TYPE_SUBSUMES.get(t, {t})
                                reg_expanded = set()
                                for t in reg_types:
                                    reg_expanded |= TYPE_SUBSUMES.get(t, {t})
                                # A conflict is when there's no overlap after expansion
                                if not api_expanded & reg_expanded:
                                    issues.append({
                                        "type": "type_conflict",
                                        "overload_index": ov_idx,
                                        "param_index": i,
                                        "param_name": ap.get("name", f"arg{i}"),
                                        "api_type": ap["type"],
                                        "registry_type": reg_type,
                                        "registry_mapped": mapped,
                                        "severity": "low" if not is_verified else "medium"
                                    })

            if issues:
                review_report.append({
                    "name": api_entry["name"],
                    "file": file_label,
                    "issues": issues,
                    "error_strings": reg.get("error_strings", []),
                    "handler": reg.get("handler"),
                    "registry_min_args": reg.get("min_args"),
                    "registry_max_args": reg.get("max_args"),
                })
                stats["tier2_issues_flagged"] += len(issues)

    build_tier2(gsc_map, csc_map, "t7_api_gsc")
    build_tier2(csc_map, gsc_map, "t7_api_csc")

    # ── TIER 3: New Entry Candidates ──────────────────────────────────────

    all_api_names = gsc_names | csc_names

    for name_lower, reg in reg_map.items():
        if name_lower in all_api_names:
            continue

        # Filter: must have valid arg counts
        min_args = reg.get("min_args")
        max_args = reg.get("max_args")
        if min_args is None or max_args is None:
            continue

        new_entry = build_new_entry(reg)
        targets = classify_for_api(reg, gsc_names, csc_names)

        if "gsc" in targets:
            gsc_out["api"].append(new_entry)
            stats["tier3_gsc_added"] += 1

        if "csc" in targets:
            csc_entry = copy.deepcopy(new_entry)
            csc_out["api"].append(csc_entry)
            stats["tier3_csc_added"] += 1

    # ── Sort API entries by name ──────────────────────────────────────────

    gsc_out["api"].sort(key=lambda e: e["name"].lower())
    csc_out["api"].sort(key=lambda e: e["name"].lower())

    # Sort review report by severity (high first) then name
    severity_order = {"high": 0, "medium": 1, "low": 2}
    review_report.sort(key=lambda r: (
        min(severity_order.get(i.get("severity", "low"), 3) for i in r["issues"]),
        r["name"].lower()
    ))

    # ── Write Outputs ─────────────────────────────────────────────────────

    with open(OUTPUT_GSC, "w", encoding="utf-8") as f:
        json.dump(gsc_out, f, indent=4, ensure_ascii=False)
        f.write("\n")

    with open(OUTPUT_CSC, "w", encoding="utf-8") as f:
        json.dump(csc_out, f, indent=4, ensure_ascii=False)
        f.write("\n")

    with open(OUTPUT_REVIEW, "w", encoding="utf-8") as f:
        json.dump(review_report, f, indent=2, ensure_ascii=False)
        f.write("\n")

    with open(OUTPUT_CHANGELOG, "w", encoding="utf-8") as f:
        json.dump(changelog, f, indent=2, ensure_ascii=False)
        f.write("\n")

    # ── Summary ───────────────────────────────────────────────────────────

    print("=" * 60)
    print("Registry-Driven API Enrichment — Summary")
    print("=" * 60)
    print()
    print("TIER 1 — Auto-applied changes:")
    print(f"  Parameter types backfilled:  {stats['tier1_param_types_added']}")
    print(f"  Return types added:          {stats['tier1_return_types_added']}")
    print(f"  Mandatory flags fixed:       {stats['tier1_mandatory_fixed']}")
    print(f"  CalledOn backfilled:         {stats['tier1_calledon_added']}")
    print()
    print("TIER 2 — Review report:")
    print(f"  Total issues flagged:        {stats['tier2_issues_flagged']}")
    print(f"  Entries with issues:         {len(review_report)}")
    print()
    print("TIER 3 — New entries:")
    print(f"  Added to GSC:                {stats['tier3_gsc_added']}")
    print(f"  Added to CSC:                {stats['tier3_csc_added']}")
    print()
    print("Output files:")
    print(f"  {OUTPUT_GSC}")
    print(f"  {OUTPUT_CSC}")
    print(f"  {OUTPUT_REVIEW}")
    print(f"  {OUTPUT_CHANGELOG}")
    print()

    # Breakdown of review report
    issue_types = {}
    for r in review_report:
        for i in r["issues"]:
            key = f"{i['severity']}:{i['type']}"
            issue_types[key] = issue_types.get(key, 0) + 1
    print("Review report breakdown:")
    for key in sorted(issue_types.keys()):
        print(f"  {key}: {issue_types[key]}")


if __name__ == "__main__":
    main()
