#!/usr/bin/env python3
"""
Batch process autogenerated entries.
These already have descriptions and types - they just need convention fixes:
1. PascalCase name segments
2. Descriptions end with period
3. Parameter descriptions end with period
4. CalledOn descriptions end with period
5. American English
6. int returns that are clearly boolean -> bool
7. Mark as processed with appropriate confidence
"""
import json, re, sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()

BRITISH_TO_AMERICAN = {
    "colour": "color", "colours": "colors", "coloured": "colored",
    "favour": "favor", "favourite": "favorite",
    "honour": "honor", "behaviour": "behavior",
    "centre": "center", "metre": "meter",
    "defence": "defense", "offence": "offense",
    "analyse": "analyze", "organise": "organize",
    "recognise": "recognize", "initialise": "initialize",
    "normalise": "normalize", "serialise": "serialize",
    "grey": "gray", "armour": "armor", "mould": "mold",
}

# Patterns that indicate an int return is really a boolean
BOOL_RETURN_PATTERNS = [
    r"^returns?\s+(true|1)\s+(if|when)",
    r"^(true|1)\s+if",
    r"^whether\b",
    r"^checks?\s+(if|whether)",
    r"^determines?\s+(if|whether)",
    r"returns?\s+(true|false|0|1)\b.*\b(true|false|0|1)\b",
]


def fix_pascal_case(name):
    """Fix segments to PascalCase, preserving underscores."""
    if "_" in name:
        segments = name.split("_")
        return "_".join(s[0].upper() + s[1:] if s else s for s in segments)
    else:
        if name and name[0].islower():
            return name[0].upper() + name[1:]
        return name


def fix_description(desc):
    """Ensure description ends with period and uses American English."""
    if not desc or not desc.strip():
        return desc
    desc = desc.strip()
    # Fix British spellings
    for brit, amer in BRITISH_TO_AMERICAN.items():
        # Word boundary replacement
        desc = re.sub(r'\b' + brit + r'\b', amer, desc, flags=re.IGNORECASE)
    # Add period if missing
    if not desc.endswith(".") and not desc.endswith("?") and not desc.endswith("!"):
        desc = desc + "."
    return desc


def is_bool_return(entry):
    """Check if an int return type is really a boolean based on description."""
    for ov in entry.get("overloads", []):
        ret = ov.get("returns")
        if not ret or ret.get("void"):
            continue
        ret_type = ret.get("type", {})
        if not ret_type or ret_type.get("dataType") != "int":
            continue
        # Check return description
        ret_desc = (ret.get("description") or "").lower()
        for pattern in BOOL_RETURN_PATTERNS:
            if re.search(pattern, ret_desc):
                return True
        # Check function description
        func_desc = (entry.get("description") or "").lower()
        for pattern in BOOL_RETURN_PATTERNS:
            if re.search(pattern, func_desc):
                return True
    return False


def process_entry(entry):
    """Process an autogenerated entry, return (modified_entry, confidence)."""
    modified = False
    confidence = "high"

    # Fix name casing
    old_name = entry["name"]
    new_name = fix_pascal_case(old_name)
    if new_name != old_name:
        entry["name"] = new_name
        modified = True

    # Fix description
    old_desc = entry.get("description", "")
    new_desc = fix_description(old_desc)
    if new_desc != old_desc:
        entry["description"] = new_desc
        modified = True

    # Check if int return is really bool
    if is_bool_return(entry):
        for ov in entry.get("overloads", []):
            ret = ov.get("returns")
            if ret and not ret.get("void"):
                ret_type = ret.get("type", {})
                if ret_type and ret_type.get("dataType") == "int":
                    ret_type["dataType"] = "bool"
                    modified = True

    # Fix parameter descriptions
    for ov in entry.get("overloads", []):
        # CalledOn
        co = ov.get("calledOn")
        if co and isinstance(co, dict):
            co_desc = co.get("description")
            if co_desc:
                new_co_desc = fix_description(co_desc)
                if new_co_desc != co_desc:
                    co["description"] = new_co_desc
                    modified = True

        # Parameters
        for param in ov.get("parameters", []):
            p_desc = param.get("description", "")
            if p_desc:
                new_p_desc = fix_description(p_desc)
                if new_p_desc != p_desc:
                    param["description"] = new_p_desc
                    modified = True

            # Check for spaces in param names (fix to camelCase)
            p_name = param.get("name", "")
            if " " in p_name:
                # "team mask" -> "teamMask"
                parts = p_name.split()
                new_p_name = parts[0].lower() + "".join(p.capitalize() for p in parts[1:])
                param["name"] = new_p_name
                modified = True

        # Returns
        ret = ov.get("returns")
        if ret and not ret.get("void"):
            ret_desc = ret.get("description")
            if ret_desc:
                new_ret_desc = fix_description(ret_desc)
                if new_ret_desc != ret_desc:
                    ret["description"] = new_ret_desc
                    modified = True

    # Determine confidence
    has_desc = bool((entry.get("description") or "").strip())
    has_all_param_descs = True
    has_all_param_types = True
    for ov in entry.get("overloads", []):
        for p in ov.get("parameters", []):
            if not p.get("description", "").strip():
                has_all_param_descs = False
            if not p.get("type"):
                has_all_param_types = False

    if has_desc and has_all_param_descs and has_all_param_types:
        confidence = "high"
    elif has_desc:
        confidence = "medium"
    else:
        confidence = "low"

    # Update flags
    entry["flags"] = ["processed"]
    entry["confidence"] = confidence

    return entry, confidence


def main():
    for file_key in ["gsc", "csc"]:
        path = SCRIPT_DIR / f"t7_api_{file_key}_working.json"
        with open(path) as f:
            data = json.load(f)

        counts = {"high": 0, "medium": 0, "low": 0}
        bool_fixes = 0
        name_fixes = 0
        desc_fixes = 0

        for entry in data["api"]:
            if "autogenerated" not in entry.get("flags", []):
                continue

            old_name = entry["name"]
            old_desc = entry.get("description", "")

            if is_bool_return(entry):
                bool_fixes += 1

            entry, confidence = process_entry(entry)
            counts[confidence] += 1

            if entry["name"] != old_name:
                name_fixes += 1

        with open(path, "w", newline="\n") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)
            f.write("\n")

        total = sum(counts.values())
        print(f"{file_key.upper()}: Processed {total} autogenerated entries")
        print(f"  Confidence: high={counts['high']} medium={counts['medium']} low={counts['low']}")
        print(f"  Name casing fixes: {name_fixes}")
        print(f"  Int->Bool return fixes: {bool_fixes}")


if __name__ == "__main__":
    main()
