<script lang="ts">
	import { Separator } from '$components/ui/separator/index.js';
	import { ScrollArea } from '$components/ui/scroll-area/index.js';
	import { Button } from '$components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import * as Sidebar from '$components/ui/sidebar/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';

	// @ts-ignore
	import Command from 'lucide-svelte/icons/command';
	// @ts-ignore
	import Search from 'lucide-svelte/icons/search';
	// @ts-ignore
	import Upload from 'lucide-svelte/icons/upload';
	// @ts-ignore
	import Download from 'lucide-svelte/icons/download';
	// @ts-ignore
	import Save from 'lucide-svelte/icons/save';
	// @ts-ignore
	import FolderOpen from 'lucide-svelte/icons/folder-open';
	// @ts-ignore
	import Plus from 'lucide-svelte/icons/plus';
	// @ts-ignore
	import Undo2 from 'lucide-svelte/icons/undo-2';
	// @ts-ignore
	import X from 'lucide-svelte/icons/x';

	import EditorFilters from './EditorFilters.svelte';
	import type { ScrFunction } from '$lib/models/library';
	import { getEditorContext } from '$lib/api-editor/editor.svelte';
	import { ScrLibrarySchema } from '$lib/models/library';

	const truncateString = (string = '', maxLength = 20) =>
		string.length > maxLength ? `${string.substring(0, maxLength)}…` : string;

	let editor = getEditorContext();
	let library = $derived(editor.library);
	let stats = $derived(editor.stats);
	let hasLibrary = $derived(editor.hasLibrary);
	let selectedFunction = $derived(editor.selectedFunction);

	let loadingSource: string | null = $state(null);
	let loadPopoverOpen = $state(false);

	let searchTerm = $state('');

	// Filter state
	let showVerified = $state(true);
	let showAutogenerated = $state(true);
	let showProblems = $state(true);
	let showBadVerifications = $state(true);
	let showDeleted = $state(true);

	let filteredData = $derived.by(() => {
		// Capture dependencies synchronously at the top
		const search = searchTerm;
		const filterVerified = showVerified;
		const filterAutogenerated = showAutogenerated;
		const filterProblems = showProblems;
		const filterBadVerifications = showBadVerifications;
		const filterDeleted = showDeleted;
		const fnMap = editor.functions;

		if (!fnMap) {
			return { entries: [] };
		}

		let w = search.replace(/[.+^${}()|[\]\\]/g, '\\$&'); // regexp escape
		const re = new RegExp(`^${w.replace(/\*/g, '.*').replace(/\?/g, '.')}$`, 'i');

		const entries = Array.from(fnMap.values()).filter((functionEditor) => {
			const apiFunction = functionEditor.function;

			// Text search filter
			const matchesSearch =
				apiFunction.name.toLowerCase().includes(search.toLowerCase()) ||
				re.test(apiFunction.name);

			if (!matchesSearch) return false;

			// Deleted filter - check first as it's a distinct state
			if (functionEditor.deleted) return filterDeleted;

			const isInvalid = functionEditor.isInvalid;
			const isVerified = functionEditor.isVerified;
			const isUnverified = functionEditor.isUnverified;

			// Filter logic: match the visual hierarchy
			if (isVerified && isInvalid) return filterBadVerifications;
			if (isInvalid) return filterProblems;
			if (isVerified) return filterVerified;
			if (isUnverified) return filterAutogenerated;

			return true;
		});

		return { entries };
	});

	let inputElement: HTMLInputElement | null = $state(null);
	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'k' && (event.ctrlKey || event.metaKey) && inputElement) {
			event.preventDefault();
			inputElement.focus();
		}
	}

	let fileInputElement: HTMLInputElement | null = $state(null);

	function handleLoadFromJSON() {
		if (stats.editedCount > 0) {
			const confirmLoad = confirm(
				'You have unsaved changes. Loading a new JSON will overwrite your current progress. Are you sure?'
			);
			if (!confirmLoad) return;
		}
		fileInputElement?.click();
	}

	async function onFileSelected(event: Event) {
		const target = event.target as HTMLInputElement;
		const file = target.files?.[0];
		if (!file) {
			return;
		}

		try {
			const text = await file.text();
			const json = JSON.parse(text);
			const validatedLibrary = await ScrLibrarySchema.parseAsync(json);
			editor.updateLibrary(validatedLibrary);
			// Reset the input so the same file can be selected again
			target.value = '';
		} catch (err) {
			console.error('Failed to load JSON:', err);
			alert('Failed to load JSON. Please ensure it follows the correct schema.');
		}
	}

	function handleSaveToJSON() {
		const exportedLibrary = editor.exportLibrary();
		if (!exportedLibrary) return;

		// Convert dates back to strings for JSON
		const json = JSON.stringify(
			{
				...exportedLibrary,
				revisedOn: exportedLibrary.revisedOn.toISOString()
			},
			null,
			4
		);

		const blob = new Blob([json], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${exportedLibrary.gameId}_api_${exportedLibrary.languageId}.json`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);

		// Reset original state of all function editors to the newly saved state
		// This clears the "edited" flag for all functions
		editor.updateLibrary(exportedLibrary);
	}

	async function loadFromApiSource(languageId: 'gsc' | 'csc') {
		if (stats.editedCount > 0) {
			const confirmLoad = confirm(
				'You have unsaved changes. Loading a new library will overwrite your current progress. Are you sure?'
			);
			if (!confirmLoad) return;
		}

		loadingSource = languageId;
		try {
			const res = await fetch(`/api/getLibrary?gameId=t7&languageId=${languageId}`);
			if (!res.ok) {
				throw new Error(`Failed to load ${languageId.toUpperCase()} library`);
			}
			const json = await res.json();
			const validatedLibrary = await ScrLibrarySchema.parseAsync(json);
			editor.updateLibrary(validatedLibrary);
		} catch (err) {
			console.error('Failed to load API source:', err);
			alert(`Failed to load ${languageId.toUpperCase()} library. Please try again.`);
		} finally {
			loadingSource = null;
		}
	}

	function handleSelectFunction(name: string) {
		editor.selectFunction(name);
	}

	function handleCreateFunction() {
		editor.createFunction();
	}

	function handleRestoreFunction(name: string, event: Event) {
		event.stopPropagation();
		editor.restoreFunction(name);
	}

	function handleUnloadLibrary() {
		if (stats.editedCount > 0) {
			const confirmUnload = confirm(
				'You have unsaved changes. Unloading will discard all your edits. Are you sure?'
			);
			if (!confirmUnload) return;
		}
		editor.unloadLibrary();
	}
</script>

<input
	type="file"
	accept="application/json"
	bind:this={fileInputElement}
	onchange={onFileSelected}
	class="hidden"
/>

<Sidebar.Root side="left" collapsible="offcanvas" variant="sidebar" class="absolute h-full">
	<Sidebar.Header class="px-4 py-4">
		<div class="flex flex-col gap-2 shrink-0">
			<div class="font-medium text-sm">Editor</div>
			{#if hasLibrary && library}
				<div
					class="flex flex-col gap-1 text-[10px] uppercase tracking-wider text-muted-foreground"
				>
					<div class="flex justify-between">
						<span>Language ID</span>
						<span class="text-foreground font-medium">{library.languageId}</span>
					</div>
					<div class="flex justify-between">
						<span>Game Identifier</span>
						<span class="text-foreground font-medium">{library.gameId}</span>
					</div>
					<div class="flex justify-between">
						<span>Revision</span>
						<span class="text-foreground font-medium">{library.revision}</span>
					</div>
					<div class="flex justify-between">
						<span>Last Revised</span>
						<span class="text-foreground font-medium">{library.revisedOn.toLocaleDateString()}</span
						>
					</div>
				</div>
			{:else}
				<div class="text-xs text-muted-foreground italic">No library loaded</div>
			{/if}
		</div>
	</Sidebar.Header>
	<Sidebar.Content class="flex flex-col gap-3 min-h-0 items-stretch grow px-4 py-4">
		{#if hasLibrary}
			<div>
				<div class="font-medium text-sm mb-2">Report</div>
				<div
					class="flex flex-col gap-1 text-[10px] uppercase tracking-wider text-muted-foreground"
				>
					<div class="flex justify-between">
						<span>Verified</span>
						<span class="text-foreground font-medium">{stats.verifiedCount}</span>
					</div>
					<div class="flex justify-between">
						<span>Autogenerated</span>
						<span class="text-foreground font-medium">{stats.autogeneratedCount}</span>
					</div>
					<div class="flex justify-between">
						<span>Problems Detected</span>
						<span class="text-foreground font-medium">{stats.invalidCount}</span>
					</div>
					<div class="flex justify-between">
						<span>Bad Verifications</span>
						<span class="text-foreground font-medium">{stats.badVerificationCount}</span>
					</div>
				</div>
			</div>
			<Separator />
			<div class="flex flex-col min-h-0 grow">
				<div class="flex items-center justify-between mb-2">
					<div class="font-medium text-sm">Functions</div>
					<Button
						variant="ghost"
						size="sm"
						class="h-6 w-6 p-0"
						title="Add new function"
						onclick={handleCreateFunction}
					>
						<Plus class="h-4 w-4" />
					</Button>
				</div>
				<ScrollArea class="w-full max-w-full min-h-0 grow">
					<div class="grid grid-flow-row auto-rows-max w-full">
						{#each filteredData.entries as fnEditor}
							{@const apiFunction = fnEditor.function}
							{@const isSelected = selectedFunction === apiFunction.name.toLowerCase()}
							{@const isDeleted = fnEditor.deleted}
							<div class="flex items-center">
								<Button
									variant={isSelected ? 'secondary' : 'ghost'}
									size={'sm'}
									class="flex-1 justify-start font-normal {isSelected
										? 'text-foreground'
										: 'text-muted-foreground'} {isDeleted ? 'opacity-50' : ''}"
									onclick={() => !isDeleted && handleSelectFunction(apiFunction.name)}
									disabled={isDeleted}
								>
									{#if isDeleted}
										<div
											class="mr-2 h-2 w-2 shrink-0 rounded-full bg-zinc-500"
											title="This function is marked for deletion"
										></div>
									{:else if fnEditor.isNew}
										<div
											class="mr-2 h-2 w-2 shrink-0 rounded-full bg-green-500"
											title="This is a new function"
										></div>
									{:else if fnEditor.isInvalid}
										<div
											class="mr-2 h-2 w-2 shrink-0 rounded-full {fnEditor.isVerified
												? 'bg-red-600'
												: 'bg-amber-700'}"
											title={fnEditor.isVerified
												? 'This verified function has problems'
												: 'This function has problems'}
										></div>
									{:else if fnEditor.isUnverified}
										<div
											class="mr-2 h-2 w-2 shrink-0 rounded-full bg-yellow-400"
											title="This function is unverified"
										></div>
									{/if}
									<span class={isDeleted ? 'line-through' : ''}>
										{truncateString(apiFunction.name, 25)}
									</span>
								</Button>
								{#if isDeleted}
									<Button
										variant="ghost"
										size="sm"
										class="h-7 w-7 p-0 shrink-0"
										title="Restore function"
										onclick={() => editor.restoreFunction(apiFunction.name)}
									>
										<Undo2 class="h-3 w-3" />
									</Button>
								{/if}
							</div>
						{/each}
					</div>
				</ScrollArea>
			</div>

			<div class="flex gap-2 shrink-0">
				<div class="relative w-full">
					<Search
						class="absolute left-2.5 top-[50%] -translate-y-[50%] h-4 w-4 text-muted-foreground pointer-events-none"
					/>
					<Input
						type="search"
						placeholder="Search..."
						class="w-full rounded-lg bg-background pl-8 pr-12"
						bind:value={searchTerm}
						bind:ref={inputElement}
					/>
					<div
						class="absolute right-2.5 top-[50%] -translate-y-[50%] flex items-center gap-1 rounded-md px-1 py-0.5 text-muted-foreground bg-muted text-xs pointer-events-none"
					>
						<Command class="w-3.5 h-3.5" />
						K
					</div>
				</div>
				<EditorFilters
					bind:showVerified
					bind:showAutogenerated
					bind:showProblems
					bind:showBadVerifications
					bind:showDeleted
				/>
			</div>
			<Separator />
		{/if}
		<div>
			<div class="font-medium text-sm mb-2">Actions</div>
			{#if hasLibrary}
				<div class="text-xs text-muted-foreground mb-2 italic">
					{#if stats.editedCount > 0}
						{stats.editedCount} function{stats.editedCount === 1 ? '' : 's'} edited.
					{:else}
						No changes applied.
					{/if}
				</div>
			{/if}
			<div class="flex gap-2">
				<Popover.Root bind:open={loadPopoverOpen}>
					<Popover.Trigger>
						{#snippet child({ props })}
							<Button
								variant="outline"
								size="sm"
								class="flex-1 text-xs"
								disabled={loadingSource !== null}
								{...props}
							>
								<FolderOpen class="w-3.5 h-3.5 mr-1.5" />
								{loadingSource ? 'Loading...' : 'Load'}
							</Button>
						{/snippet}
					</Popover.Trigger>
					<Popover.Content class="w-48 p-2" align="start">
						<div class="flex flex-col gap-1">
							<Button
								variant="ghost"
								size="sm"
								class="w-full text-xs justify-start"
								onclick={() => {
									loadFromApiSource('gsc');
									loadPopoverOpen = false;
								}}
							>
								<Download class="w-3.5 h-3.5 mr-2" />
								Load Latest GSC
							</Button>
							<Button
								variant="ghost"
								size="sm"
								class="w-full text-xs justify-start"
								onclick={() => {
									loadFromApiSource('csc');
									loadPopoverOpen = false;
								}}
							>
								<Download class="w-3.5 h-3.5 mr-2" />
								Load Latest CSC
							</Button>
							<Separator class="my-1" />
							<Button
								variant="ghost"
								size="sm"
								class="w-full text-xs justify-start"
								onclick={() => {
									handleLoadFromJSON();
									loadPopoverOpen = false;
								}}
							>
								<Upload class="w-3.5 h-3.5 mr-2" />
								Load from File
							</Button>
						</div>
					</Popover.Content>
				</Popover.Root>
				<Button
					variant="outline"
					size="sm"
					onclick={handleSaveToJSON}
					class="flex-1 text-xs"
					disabled={!hasLibrary}
				>
					<Save class="w-3.5 h-3.5 mr-1.5" />
					Download
				</Button>
			</div>
			{#if hasLibrary}
				<div class="flex gap-2 mt-2">
					<Button
						variant="outline"
						size="sm"
						onclick={handleUnloadLibrary}
						class="flex-1 text-xs"
					>
						<X class="w-3.5 h-3.5 mr-1.5" />
						Unload
					</Button>
				</div>
			{/if}
		</div>
	</Sidebar.Content>

	<Sidebar.Footer
		class="text-muted-foreground text-xs inline-flex justify-between shrink-0 px-4 py-4"
	>
		A part of the GSCode project.
		<a
			href="https://ko-fi.com/blakintosh"
			target="_blank"
			rel="noreferrer"
			class="text-primary hover:underline"
		>
			Donate
		</a>
	</Sidebar.Footer>

	<Sidebar.Rail />
</Sidebar.Root>

<svelte:window onkeydown={handleKeyDown} />
