<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';

	import Filter from 'lucide-svelte/icons/filter';

	interface Props {
		showVerified: boolean;
		showAutogenerated: boolean;
		showProblems: boolean;
		showBadVerifications: boolean;
		showDeleted: boolean;
	}

	let {
		showVerified = $bindable(true),
		showAutogenerated = $bindable(true),
		showProblems = $bindable(true),
		showBadVerifications = $bindable(true),
		showDeleted = $bindable(true)
	}: Props = $props();

	let hasActiveFilters = $derived(
		!showVerified || !showAutogenerated || !showProblems || !showBadVerifications || !showDeleted
	);
</script>

<Popover.Root>
	<Popover.Trigger>
		{#snippet child({ props })}
			<Button variant="outline" size="icon" class="h-9 w-9 shrink-0 relative" {...props}>
				<Filter class="h-4 w-4" />
				{#if hasActiveFilters}
					<span class="absolute -top-1 -right-1 h-2 w-2 rounded-full bg-primary"></span>
				{/if}
			</Button>
		{/snippet}
	</Popover.Trigger>
	<Popover.Content class="w-56" align="end">
		<div class="flex flex-col gap-4">
			<div class="text-sm font-medium">Filter Functions</div>
			<div class="flex flex-col gap-3">
				<label class="flex items-center gap-2 cursor-pointer">
					<Checkbox bind:checked={showVerified} />
					<span class="text-sm">Show Verified</span>
				</label>
				<label class="flex items-center gap-2 cursor-pointer">
					<Checkbox bind:checked={showAutogenerated} />
					<span class="text-sm">Autogenerated</span>
				</label>
				<label class="flex items-center gap-2 cursor-pointer">
					<Checkbox bind:checked={showProblems} />
					<span class="text-sm">Problems Detected</span>
				</label>
				<label class="flex items-center gap-2 cursor-pointer">
					<Checkbox bind:checked={showBadVerifications} />
					<span class="text-sm">Bad Verifications</span>
				</label>
				<label class="flex items-center gap-2 cursor-pointer">
					<Checkbox bind:checked={showDeleted} />
					<span class="text-sm">Deleted</span>
				</label>
			</div>
		</div>
	</Popover.Content>
</Popover.Root>
