<script lang="ts">
	import { Button } from '$components/ui/button';
	import * as Alert from '$lib/components/ui/alert/index.js';
	// @ts-ignore
	import BadgeCheck from "lucide-svelte/icons/badge-check";
	// @ts-ignore
	import EyeOff from "lucide-svelte/icons/eye-off";
	// @ts-ignore
	import MessageCircleQuestion from "lucide-svelte/icons/message-circle-question";
	import FlagAlert from './FlagAlert.svelte';

	export let flags: string[] = [];
</script>

{#if flags.includes('autogenerated')}
	<FlagAlert Icon={MessageCircleQuestion} title={"Unverified"} description={`
		This function's documentation was auto-generated from Treyarch's API, which is known to
		contain errors.
	`}/>
{/if}

{#if flags.includes('verified')}
	<FlagAlert Icon={BadgeCheck} title={"Community contribution"} description={`
		This function's documentation has been verified or corrected by a member of the community.
	`}/>
{/if}

{#if flags.includes('unlisted')}
	<FlagAlert Icon={EyeOff} title={"Unlisted"} description={`
		This function has been unlisted. It is unlikely to be functional and/or useful.
	`}/>
{/if}
