<script lang="ts">
	import type { FunctionEditor } from '$lib/api-editor/function-editor.svelte';
	// @ts-ignore
	import CircleHelp from 'lucide-svelte/icons/circle-help';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import * as Tooltip from '$lib/components/ui/tooltip/index.js';

	interface Props {
		functionEditor: FunctionEditor;
	}

	let { functionEditor }: Props = $props();

	const flags = [
		{
			id: 'autogenerated',
			label: 'Autogenerated',
			tooltip: "This function was auto-generated from Treyarch's API and may contain errors."
		},
		{
			id: 'verified',
			label: 'Verified',
			tooltip: 'This function was verified by a member of the community.'
		},
		{
			id: 'broken',
			label: 'Broken',
			tooltip: 'This function is known to be broken or non-functional.'
		},
		{
			id: 'unlisted',
			label: 'Unlisted',
			tooltip: 'This function has been unlisted. It is unlikely to be functional and/or useful.'
		}
	];
</script>

<div>
	<div class="font-medium text-sm mb-3">Function Flags</div>
	<div class="flex flex-col gap-3">
		{#each flags as flag}
			<div class="flex items-center justify-between gap-2">
				<label
					for={flag.id}
					class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer flex-grow"
				>
					{flag.label}
				</label>
				<div class="flex items-center gap-2">
					<Tooltip.Provider>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<CircleHelp class="size-3.5 text-muted-foreground" />
							</Tooltip.Trigger>
							<Tooltip.Content>
								<p class="max-w-xs text-xs">{flag.tooltip}</p>
							</Tooltip.Content>
						</Tooltip.Root>
					</Tooltip.Provider>
					<Checkbox
						id={flag.id}
						checked={functionEditor.function.flags.includes(flag.id)}
						onCheckedChange={() => functionEditor.toggleFlag(flag.id)}
					/>
				</div>
			</div>
		{/each}
	</div>
</div>

