<script lang="ts">
	import type { FunctionEditor } from '$lib/api-editor/function-editor.svelte';
	// @ts-ignore
	import CircleHelp from 'lucide-svelte/icons/circle-help';
	import { Checkbox } from '$lib/components/ui/checkbox/index.js';
	import * as Tooltip from '$lib/components/ui/tooltip/index.js';
	import * as Select from '$lib/components/ui/select/index.js';

	interface Props {
		functionEditor: FunctionEditor;
	}

	let { functionEditor }: Props = $props();

	const flags = [
		{
			id: 'autogenerated',
			label: 'Autogenerated',
			tooltip: "This function was auto-generated from Treyarch's API and may contain errors."
		},
		{
			id: 'processed',
			label: 'Processed',
			tooltip: 'This function was batch-processed and reviewed. Check the confidence level.'
		},
		{
			id: 'verified',
			label: 'Verified',
			tooltip: 'This function was verified by a member of the community.'
		},
		{
			id: 'broken',
			label: 'Broken',
			tooltip: 'This function is known to be broken or non-functional.'
		},
		{
			id: 'unlisted',
			label: 'Unlisted',
			tooltip: 'This function has been unlisted. It is unlikely to be functional and/or useful.'
		},
		{
			id: 'devblock',
			label: 'Dev Block',
			tooltip: 'This function is only available inside developer blocks (devblocks activated via dvar).'
		}
	];

	const confidenceLevels = [
		{ value: 'high', label: 'High' },
		{ value: 'medium', label: 'Medium' },
		{ value: 'low', label: 'Low' }
	];

	let showConfidence = $derived(
		functionEditor.function.flags.includes('processed') ||
			(functionEditor.function.flags.includes('verified') && functionEditor.function.confidence != null)
	);
</script>

<div>
	<div class="font-medium text-sm mb-3">Function Flags</div>
	<div class="flex flex-col gap-3">
		{#each flags as flag}
			<div class="flex items-center justify-between gap-2">
				<label
					for={flag.id}
					class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer flex-grow"
				>
					{flag.label}
				</label>
				<div class="flex items-center gap-2">
					<Tooltip.Provider>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<CircleHelp class="size-3.5 text-muted-foreground" />
							</Tooltip.Trigger>
							<Tooltip.Content>
								<p class="max-w-xs text-xs">{flag.tooltip}</p>
							</Tooltip.Content>
						</Tooltip.Root>
					</Tooltip.Provider>
					<Checkbox
						id={flag.id}
						checked={functionEditor.function.flags.includes(flag.id)}
						onCheckedChange={() => functionEditor.toggleFlag(flag.id)}
					/>
				</div>
			</div>
		{/each}

		{#if showConfidence}
			<div class="flex items-center justify-between gap-2 mt-1">
				<label
					for="confidence"
					class="text-sm font-medium leading-none cursor-pointer flex-grow"
				>
					Confidence
				</label>
				<Select.Root
					type="single"
					value={functionEditor.function.confidence ?? undefined}
					onValueChange={(value: string) => functionEditor.setConfidence(value as 'low' | 'medium' | 'high' | null)}
				>
					<Select.Trigger class="w-28 h-8 text-xs">
						{functionEditor.function.confidence
							? confidenceLevels.find((l) => l.value === functionEditor.function.confidence)?.label ?? 'Select...'
							: 'Select...'}
					</Select.Trigger>
					<Select.Content>
						{#each confidenceLevels as level}
							<Select.Item value={level.value}>{level.label}</Select.Item>
						{/each}
					</Select.Content>
				</Select.Root>
			</div>
		{/if}
	</div>
</div>

